import {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter,Route,Routes,Link,useNavigate} from 'react-router-dom';
import {MembershipExpired} from '../src/components/admin/MembershipExpired';
import SubscriptionCheckout, {type CheckoutSubmission} from '../src/components/billing/SubscriptionCheckout';
import '../src/index.css';

if(!import.meta.env.DEV)throw new Error('Simulación disponible solo en desarrollo.');
// Simulación visual: no usa API ni envía imágenes.
const params=new URLSearchParams(location.search);
function Billing(){const navigate=useNavigate();const [split,setSplit]=useState(false),[paying,setPaying]=useState(false),[amount,setAmount]=useState('20.00'),[error,setError]=useState('');const [payments,setPayments]=useState<{cents:number;reference:string;method:string}[]>([]);const total=3999;const remaining=total-payments.reduce((n,p)=>n+p.cents,0);const cents=Math.round(Number(amount)*100);const money=(n:number)=>`€${(n/100).toFixed(2)}`;
function continuePayment(){if(!/^\d+(\.\d{1,2})?$/.test(amount)||cents<=0||cents>remaining){setError('Escribe un monto válido, con máximo dos decimales, que no supere el saldo.');return}if(payments.length>=3||(payments.length===2&&cents!==remaining)){setError('El tercer comprobante debe completar todo el saldo.');return}setError('');setPaying(true)}
async function submit(payment:CheckoutSubmission){if(split){if(payments.some(p=>p.reference===payment.reference&&p.method===payment.method))throw new Error('Esta referencia ya fue registrada.');setPayments(p=>[...p,{cents,reference:payment.reference,method:payment.method}]);setAmount(((remaining-cents)/100).toFixed(2));setPaying(false)}else await new Promise(r=>setTimeout(r,600))}
if(split&&!paying)return <main className="qt-checkout"><div style={{maxWidth:480,margin:'32px auto'}}><button className="qt-pay-back" onClick={()=>payments.length?navigate('/'):setSplit(false)}>← Volver</button><section className="qt-pay-panel" style={{marginTop:20}}><span className="qt-pay-eyebrow">OPERATIONS · MENSUALIDAD</span><h1 style={{fontSize:26,fontWeight:600,marginBottom:12}}>Paga en partes</h1><p className="qt-pay-intro">Puedes hacerlo en dos partes. Cada abono lleva su comprobante; tienes un máximo de tres para completar el total.</p><div className="qt-pay-amount"><span>Total del plan: {money(total)}</span><span>Enviado para revisión: {money(total-remaining)}</span><strong>Falta {money(remaining)}</strong></div><p className="qt-pay-help">{payments.length}/3 comprobantes · Los montos enviados todavía no son pagos confirmados.</p>{payments.map((p,i)=><div key={i} className="qt-pay-recap"><strong>Abono {i+1} · {money(p.cents)}</strong><span>Ref. {p.reference} · Pendiente de revisión</span></div>)}{remaining>0?<><label className="qt-pay-label">Monto de este abono (€)<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value.replace(',','.'))}/></label>{payments.length===2&&<p className="qt-pay-help">Este último abono debe cubrir {money(remaining)}.</p>}{error&&<p role="alert" className="qt-pay-error">{error}</p>}<button className="qt-pay-primary" onClick={continuePayment}>Continuar con este abono</button></>:<><p role="status" className="qt-pay-intro">Completaste el monto solicitado. En un pago real, los comprobantes quedarían pendientes de verificación.</p><button className="qt-pay-primary" onClick={()=>navigate('/')}>Terminar simulación</button></>}</section></div></main>;
return <SubscriptionCheckout preview planName="Operations" periodLabel="Suscripción mensual" totalLabel={split?money(cents):"€39,99"} restaurantName="Casa Oliva" accounts={{pagoMovil:{banco:'Banco de ejemplo',telefono:'0412-0000000',cedula:'J-00000000-0',titular:'Cuenta de demostración'},binance:{id:'ID de demostración',correo:'pagos@example.invalid'},bankTransfer:{banco:'Banco de ejemplo',cuenta:'0000 0000 00 0000000000',titular:'Cuenta de demostración',rif:'J-00000000-0'}}} methods={[{id:'PAGO_MOVIL',amountLabel:split?`Bs. ${(cents).toFixed(2)}`:'Bs. 3.999,00',rateLabel:'Tasa de ejemplo: 1 EUR = Bs. 100,00'},{id:'BINANCE',amountLabel:split?`${(cents/100*1.1).toFixed(2)} USDT`:'43,99 USDT',rateLabel:'Equivalencia ilustrativa · No es una cotización'},{id:'BANK_TRANSFER',amountLabel:split?`Bs. ${(cents).toFixed(2)}`:'Bs. 3.999,00',rateLabel:'Tasa de ejemplo: 1 EUR = Bs. 100,00'}]} onInstallments={!split?()=>setSplit(true):undefined} onBack={()=>split?setPaying(false):navigate('/')} onSubmit={submit}/>}
function Preview(){const navigate=useNavigate();return <><div role="note" style={{padding:'10px 16px',textAlign:'center',background:'#fff4db',color:'#74531d',fontSize:12}}>SIMULACIÓN · Datos ficticios · No realices transferencias. La imagen permanece en tu navegador.</div><Routes><Route path="/" element={<MembershipExpired restaurantName="Casa Oliva" periodEnd="2026-09-28T16:00:00Z" suspended={params.has('suspended')} canPay={!params.has('staff')} onLogout={()=>navigate('/fin')}/>}/><Route path="/admin/billing" element={<Billing/>}/><Route path="/fin" element={<div style={{padding:40,textAlign:'center'}}><p>Fin de la simulación. Tu sesión real no cambió.</p><Link to="/">Volver al aviso</Link></div>}/></Routes></>}
createRoot(document.getElementById('root')!).render(<MemoryRouter><Preview/></MemoryRouter>);
