import {useState,type ReactNode} from 'react';
import type {CheckoutSubmission} from './SubscriptionCheckout';
interface Props {total:number;symbol:string;payments:{amountUsd:string;paymentReference:string}[];onBack:()=>void;onPay:(amount:number,payment:CheckoutSubmission)=>Promise<void>;renderCheckout:(amount:number,onSubmit:(payment:CheckoutSubmission)=>Promise<void>,onBack:()=>void)=>ReactNode}
export default function InstallmentCheckout({total,symbol,payments,onBack,onPay,renderCheckout}:Props){
 const paid=payments.reduce((n,p)=>n+Math.round(Number(p.amountUsd)*100),0);const remaining=Math.max(0,Math.round(total*100)-paid);
 const [amount,setAmount]=useState(''),[paying,setPaying]=useState(false),[error,setError]=useState('');
 const money=(cents:number)=>`${symbol}${(cents/100).toFixed(2)}`;const cents=Math.round(Number(amount)*100);
 function next(){if(!/^\d+(\.\d{1,2})?$/.test(amount)||cents<=0||cents>remaining){setError('Escribe un monto válido, con máximo dos decimales, que no supere el saldo.');return}if(payments.length>=3||(payments.length===2&&cents!==remaining)){setError('El tercer comprobante debe completar todo el saldo.');return}setError('');setPaying(true)}
 if(paying)return renderCheckout(cents/100,async payment=>{await onPay(cents/100,payment);setPaying(false);setAmount('')},()=>setPaying(false));
 return <main className="qt-checkout"><div style={{maxWidth:480,margin:'24px auto'}}><header className="qt-pay-header"><span className="qt-pay-brand"><img src="/logo/logo-central.png?v=20261002" alt="QuickTap" width="140" height="28"/><span>pagos</span></span></header><button className="qt-pay-back" onClick={onBack}>← Volver</button><section className="qt-pay-panel" style={{marginTop:16}}><h1 style={{fontSize:26,fontWeight:600,marginBottom:12}}>Paga en partes</h1><p className="qt-pay-intro text-base">Puedes pagar en dos partes, con un máximo de tres comprobantes para completar tu mensualidad.</p><div className="qt-pay-amount"><span>Total solicitado: {money(Math.round(total*100))}</span><span>Enviado para revisión: {money(paid)}</span><strong>Falta {money(remaining)}</strong></div><p className="qt-pay-help text-xs">{payments.length}/3 comprobantes · Pendientes de verificación</p>{payments.map((p,i)=><div className="qt-pay-recap" key={i}><strong>Abono {i+1} · {money(Math.round(Number(p.amountUsd)*100))}</strong><span>Ref. {p.paymentReference}</span></div>)}{remaining>0&&payments.length<3?<><label className="qt-pay-label text-sm font-medium">Monto de este abono ({symbol})<input inputMode="decimal" value={amount} placeholder={(remaining/100).toFixed(2)} onChange={e=>setAmount(e.target.value.replace(',','.'))}/></label>{payments.length===2&&<p className="qt-pay-help text-xs">El último abono debe cubrir {money(remaining)}.</p>}{error&&<p role="alert" className="qt-pay-error text-xs">{error}</p>}<button className="qt-pay-primary" onClick={next}>Continuar con este abono</button></>:<p role="status" className="qt-pay-intro text-base">{remaining===0?'Completaste el monto solicitado. Revisaremos tus comprobantes antes de confirmar la renovación.':'Ya hay tres comprobantes. Contacta al equipo para revisar el saldo.'}</p>}</section></div></main>
}
