import { PLAN_CONTENT } from '../landing/PlanCards.shared';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowLeft,ArrowRight,Check,Copy,Landmark,Smartphone,Wallet,Upload, X, Loader2} from 'lucide-react';
import {paymentMethodLines,PAYMENT_METHOD_LABEL,type PlatformPaymentMethods,type SubscriptionPaymentMethod} from '@/utils/plans';
import './subscription-checkout.css';

export interface CheckoutMethod {id:SubscriptionPaymentMethod; amountLabel:string; rateLabel?:string; amountTitle?:string}
export interface CheckoutSubmission {method:SubscriptionPaymentMethod; reference:string; proof:File; contactName?:string; contactEmail?:string; contactPhone?:string; restaurantName?:string}
interface Props {
  beforePayment?:ReactNode; canContinue?:boolean;
  includedPlan?: string; planName:string; periodLabel:string; totalLabel:string; restaurantName:string;
  methods:CheckoutMethod[]; accounts:PlatformPaymentMethods; preview?:boolean;
  prefillName?:string; prefillEmail?:string; collectContact?:boolean; collectRestaurant?:boolean; onInstallments?:()=>void; onAutomated?:()=>void;
  onBack:()=>void; onSubmit:(payment:CheckoutSubmission)=>Promise<void>;
}
const icons={PAGO_MOVIL:Smartphone,BANK_TRANSFER:Landmark,BINANCE:Wallet};
const steps=['Método','Datos de pago','Comprobante'];

/** Presentación independiente: el adaptador de facturación aportará cotización y envío reales. */
export default function SubscriptionCheckout({includedPlan,beforePayment,canContinue=true,planName,periodLabel,totalLabel,restaurantName,methods,accounts,preview=false,prefillName="",prefillEmail="",collectContact=false,collectRestaurant=false,onInstallments,onAutomated,onBack,onSubmit}:Props){
 const [name,setName]=useState(prefillName),[email,setEmail]=useState(prefillEmail),[phone,setPhone]=useState(''),[business,setBusiness]=useState('');
 const [step,setStep]=useState(0),[method,setMethod]=useState<SubscriptionPaymentMethod|undefined>(methods[0]?.id);
 const [reference,setReference]=useState(''),[proof,setProof]=useState<File|null>(null),[image,setImage]=useState('');
 const [busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const heading=useRef<HTMLHeadingElement>(null),fileInput=useRef<HTMLInputElement>(null);
 const selected=methods.find(m=>m.id===method);
 useEffect(()=>{if(!methods.some(m=>m.id===method))setMethod(methods[0]?.id)},[methods,method]);
 useEffect(()=>{if(!proof){setImage('');return}const url=URL.createObjectURL(proof);setImage(url);return()=>URL.revokeObjectURL(url)},[proof]);
 useEffect(()=>{heading.current?.focus()},[step,done]);
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice('Copiado. Ya puedes pegarlo en tu banco.')}catch{setNotice('No se pudo copiar. Selecciona el dato para copiarlo manualmente.')}}
 function chooseFile(file?:File){setError('');if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('Elige una imagen JPG, PNG o WebP de hasta 5 MB.');return}setProof(file)}
 async function submit(){if(!selected||!proof||!reference.trim()){setError('Añade la referencia y el comprobante para continuar.');return}if(collectContact&&(!name.trim()||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()))){setError('Escribe tu nombre y un correo válido.');return}setBusy(true);setError('');try{await onSubmit({method:selected.id,reference:reference.trim(),proof,contactName:name.trim(),contactEmail:email.trim(),contactPhone:phone.trim(),restaurantName:business.trim()});setDone(true)}catch(e){setError(e instanceof Error?e.message:'No se pudo enviar. Tus datos siguen aquí; vuelve a intentarlo.')}finally{setBusy(false)}}
 return <main className="qt-checkout"><header className="qt-pay-header"><span className="qt-pay-brand"><img src="/logo/logo-central.png?v=20261002" alt="QuickTap" width="140" height="28"/><span>pagos</span></span><span className="qt-pay-caption">{preview?'Vista previa · Sin cobros reales':'Tu suscripción'}</span></header>
 <div className="qt-pay-layout"><aside className="qt-pay-summary"><span className="qt-pay-eyebrow">{restaurantName}</span><h1>Todo listo para <br/>seguir creciendo.</h1><p>Tu restaurante, conectado con QuickTap.</p><div className="qt-pay-plan"><span>Tu plan</span><strong>{planName}</strong><span>{periodLabel}</span><hr/><div className="qt-pay-total"><span>Total a pagar</span><b>{totalLabel}</b></div><small>El importe según tu método aparece antes de pagar.</small></div>{includedPlan && PLAN_CONTENT.some(p=>p.id===includedPlan) && <details className="qt-pay-benefits"><summary>Qué incluye {planName}</summary><p>{PLAN_CONTENT.find(p=>p.id===includedPlan)?.capacity}</p><ul>{PLAN_CONTENT.find(p=>p.id===includedPlan)?.features.map(feature=><li key={feature}>{feature}</li>)}</ul><small>Implementación asistida, capacitación presencial y configuraciones especiales se cotizan por separado.</small></details>}<div className="qt-pay-note"><Check size={18}/><span>Tu menú, productos y configuración se conservan.</span></div></aside>
 <section className="qt-pay-panel">{done?<div className="qt-pay-success"><div className="qt-pay-success-icon"><Check size={32}/></div><span className="qt-pay-eyebrow">{preview?'Así se verá la confirmación':'Comprobante recibido'}</span><h2 ref={heading} tabIndex={-1}>{preview?'Todo, en un solo lugar.':'Gracias. Revisaremos tu pago.'}</h2><p>{preview?'Esta prueba no envió un comprobante ni cambió tu plan.':'Tu solicitud está pendiente de verificación. Enviar el comprobante no activa el plan automáticamente.'}</p><div className="qt-pay-recap"><span>{planName} · {periodLabel}</span><strong>{selected?.amountLabel}</strong><span>{selected&&PAYMENT_METHOD_LABEL[selected.id]} · Ref. {reference}</span></div><button className="qt-pay-primary" onClick={onBack}>{preview?'Volver a probar':'Volver a mi cuenta'}<ArrowRight size={18}/></button></div>:<>
 <button className="qt-pay-back" disabled={busy} onClick={()=>{setError('');setNotice('');if(step)setStep(step-1);else onBack()}}><ArrowLeft size={16}/>{step?'Atrás':'Volver'}</button>
 <ol className="qt-pay-steps" aria-label="Progreso del pago">{steps.map((label,i)=><li key={label} aria-current={i===step?'step':undefined} className={i<=step?'active':''}><span>{i<step?<Check size={13}/>:i+1}</span>{label}</li>)}</ol>
 <div className="qt-pay-stage" key={step}><span className="qt-pay-eyebrow">PASO {step+1} DE 3</span><h2 ref={heading} tabIndex={-1}>{['¿Cómo prefieres pagar?','Estos son los datos.','Ya casi está.'][step]}</h2><p className="qt-pay-intro text-base">{['Elige la opción que te resulte más cómoda.','Realiza el pago desde tu banco o aplicación. Puedes copiar cada dato con un toque.','Adjunta tu comprobante y escribe la referencia del pago.'][step]}</p>
 {step===0&&beforePayment}{step===0&&<div className="qt-pay-methods" role="radiogroup" aria-label="Método de pago">{methods.map(m=>{const Icon=icons[m.id];return <button role="radio" aria-checked={method===m.id} className={method===m.id?'selected':''} key={m.id} onClick={()=>setMethod(m.id)}><span className="qt-pay-method-icon"><Icon size={23}/></span><span><strong>{PAYMENT_METHOD_LABEL[m.id]}</strong><small>{m.amountLabel}</small></span><span className="qt-pay-radio">{method===m.id&&<Check size={13}/>}</span></button>})}{!methods.length&&<p>No hay métodos disponibles. Intenta de nuevo más tarde.</p>}</div>}
 {step===1&&selected&&<><div className="qt-pay-amount"><span>{selected.amountTitle || 'Envía exactamente'}</span><strong>{selected.amountLabel}</strong><small>{selected.rateLabel||PAYMENT_METHOD_LABEL[selected.id]}</small></div><div className="qt-pay-details">{paymentMethodLines(selected.id,accounts).filter(line=>line.label!=='Titular').map(line=><div key={line.label}><span><small>{line.label}</small><strong>{line.value}</strong></span>{line.copyable&&<button aria-label={`Copiar ${line.label}`} onClick={()=>void copy(line.value)}><Copy size={17}/></button>}</div>)}</div>{preview&&<p className="qt-pay-demo text-base">Datos ficticios para revisar el diseño. No realices transferencias.</p>}</>}
 {step===2&&<>{collectContact&&<div className="qt-pay-contact"><label className="qt-pay-label text-sm font-medium">Nombre<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} disabled={busy}/></label><label className="qt-pay-label text-sm font-medium">Correo<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><label className="qt-pay-label text-sm font-medium">Teléfono (opcional)<input type="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} disabled={busy}/></label>{collectRestaurant&&<label className="qt-pay-label text-sm font-medium">Restaurante<input autoComplete="organization" value={business} onChange={e=>setBusiness(e.target.value)} disabled={busy}/></label>}</div>}<label className="qt-pay-label text-sm font-medium" htmlFor="payment-reference">Número de referencia<input id="payment-reference" autoComplete="off" maxLength={100} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Escribe la referencia de tu pago" disabled={busy}/></label><input ref={fileInput} type="file" hidden accept="image/jpeg,image/png,image/webp" onChange={e=>{chooseFile(e.target.files?.[0]);e.target.value=''}}/>{proof?<div className="qt-pay-uploaded"><img src={image} alt="Comprobante seleccionado"/><div><strong>{proof.name}</strong><button disabled={busy} onClick={()=>fileInput.current?.click()}>Cambiar imagen</button></div><button disabled={busy} aria-label="Eliminar comprobante" onClick={()=>setProof(null)}><X size={18}/></button></div>:<button className="qt-pay-upload" onClick={()=>fileInput.current?.click()}><Upload size={25}/><strong>Añadir comprobante</strong><span>Elige una foto de tu galería o un archivo</span><small>JPG, PNG o WebP · Hasta 5 MB</small></button>}<p className="qt-pay-help text-xs">Verificaremos los datos antes de activar tu plan. Conserva el comprobante hasta recibir la confirmación.</p></>}
 </div><p className="qt-pay-footer text-xs">Este pago cubre el importe y período indicados; no autoriza débitos automáticos de renovación. Para solicitar la no renovación, escribe a <a href="mailto:soporte@quicktap.club">soporte@quicktap.club</a>. <a href="/legal#terminos" target="_blank" rel="noreferrer">Condiciones</a> · <a href="/legal#privacidad" target="_blank" rel="noreferrer">Privacidad</a>.</p><div role="status" className="qt-pay-feedback">{notice}</div>{error&&<p role="alert" className="qt-pay-error text-xs">{error}</p>}<button className="qt-pay-primary" disabled={!selected||busy||!canContinue||(step===2&&(!proof||!reference.trim()))} onClick={()=>step<2?setStep(step+1):void submit()}>{busy?<><Loader2 className="qt-pay-spinner" size={18}/>Enviando comprobante…</>:<>{['Continuar','Ya hice el pago','Enviar comprobante'][step]}<ArrowRight size={18}/></>}</button>{step===0&&onAutomated&&<button className="qt-pay-alternate" onClick={onAutomated}>Pagar con pasarela automática</button>}{step===0&&onInstallments&&<button className="qt-pay-alternate" onClick={onInstallments}>Prefiero pagar en abonos</button>}<p className="qt-pay-footer text-xs">{step===0?'El siguiente paso te muestra los datos para pagar.':step===1?'¿Aún no pagaste? Puedes volver cuando estés listo.':'La confirmación del pago queda sujeta a revisión.'}</p></>}</section></div></main>
}
