/** Estados de Venezuela — usado solo para acotar la búsqueda de ubicaciones al
 * importar una lista de zonas de delivery (Ajustes → Delivery → Importar lista),
 * así "Zona Norte" en Táchira no matchea una calle homónima en otro estado. */
export const VENEZUELA_STATES = [
  'Amazonas',
  'Anzoátegui',
  'Apure',
  'Aragua',
  'Barinas',
  'Bolívar',
  'Carabobo',
  'Cojedes',
  'Delta Amacuro',
  'Distrito Capital',
  'Falcón',
  'Guárico',
  'Lara',
  'Mérida',
  'Miranda',
  'Monagas',
  'Nueva Esparta',
  'Portuguesa',
  'Sucre',
  'Táchira',
  'Trujillo',
  'La Guaira',
  'Yaracuy',
  'Zulia',
] as const;
