import { useId, useState } from 'react';
import { Search } from 'lucide-react';

const groups:Record<string,string>={
 'Arte y comunicación':'Fotografía|Videografía|Diseño gráfico|Diseño de interiores|Diseño de moda|Ilustración|Animación|Música|Canto|Producción musical|DJ|Actuación|Danza|Escritura|Periodismo|Locución|Traducción|Edición de video|Artesanía|Pintura artística|Escultura|Tatuajes|Creación de contenido|Influencer|Modelaje|Publicidad|Marketing digital|Community manager|Relaciones públicas|Organización de eventos',
 'Tecnología':'Desarrollo de software|Desarrollo web|Desarrollo de aplicaciones|Diseño UX/UI|Análisis de datos|Ciencia de datos|Inteligencia artificial|Ciberseguridad|Soporte técnico|Administración de sistemas|Redes y telecomunicaciones|Robótica|Videojuegos|Testing de software|Gestión de productos digitales',
 'Salud y bienestar':'Medicina general|Pediatría|Cardiología|Dermatología|Ginecología|Cirugía|Psiquiatría|Oftalmología|Odontología|Enfermería|Psicología|Psicopedagogía|Fisioterapia|Terapia ocupacional|Fonoaudiología|Nutrición|Farmacia|Bioanálisis|Radiología|Optometría|Veterinaria|Masoterapia|Entrenamiento personal|Yoga|Pilates|Coaching de bienestar',
 'Belleza y cuidado personal':'Peluquería|Barbería|Maquillaje|Manicure y pedicure|Estética|Cosmetología|Diseño de cejas y pestañas|Asesoría de imagen|Spa',
 'Gastronomía y turismo':'Chef|Cocina|Repostería|Panadería|Chocolatería|Barista|Bartender|Sommelier|Catering|Restaurantes|Food truck|Hotelería|Agencia de viajes|Guía turístico|Turismo|Gestión de alojamientos',
 'Negocios y finanzas':'Emprendimiento|Administración de empresas|Contabilidad|Auditoría|Finanzas|Economía|Asesoría financiera|Seguros|Ventas|Comercio electrónico|Comercio minorista|Comercio mayorista|Importación y exportación|Recursos humanos|Reclutamiento|Consultoría empresarial|Gestión de proyectos|Asistencia virtual|Secretariado|Atención al cliente|Bienes raíces|Corretaje inmobiliario',
 'Derecho y sector público':'Abogacía|Notaría|Asesoría legal|Mediación|Gestión pública|Diplomacia|Política|Trabajo social|Cooperación internacional|Organizaciones sin fines de lucro|Seguridad pública|Protección civil',
 'Educación y ciencia':'Docencia|Educación inicial|Educación primaria|Educación secundaria|Docencia universitaria|Educación especial|Clases particulares|Enseñanza de idiomas|Capacitación profesional|Investigación|Biología|Química|Física|Matemáticas|Historia|Sociología|Antropología|Geografía|Bibliotecología',
 'Ingeniería y construcción':'Arquitectura|Ingeniería civil|Ingeniería industrial|Ingeniería mecánica|Ingeniería eléctrica|Ingeniería electrónica|Ingeniería química|Ingeniería ambiental|Ingeniería de petróleo|Agrimensura|Topografía|Construcción|Albañilería|Carpintería|Ebanistería|Plomería|Electricidad|Soldadura|Herrería|Pintura de inmuebles|Refrigeración y aire acondicionado|Mantenimiento|Instalación de paneles solares|Domótica',
 'Servicios y transporte':'Mecánica automotriz|Electromecánica|Reparación de celulares|Reparación de electrodomésticos|Costura|Sastrería|Zapatería|Joyería|Relojería|Limpieza|Jardinería|Paisajismo|Fumigación|Cerrajería|Seguridad privada|Cuidado de niños|Cuidado de adultos mayores|Cuidado de mascotas|Paseo de perros|Logística|Transporte de carga|Conducción|Reparto y delivery|Mensajería|Aviación|Navegación marítima',
 'Campo y medioambiente':'Agricultura|Agronomía|Ganadería|Pesca|Acuicultura|Apicultura|Floricultura|Gestión ambiental|Reciclaje|Energías renovables',
 'Deportes y otras actividades':'Deporte profesional|Entrenamiento deportivo|Arbitraje|Gestión deportiva|Recreación|Guía de montaña|Estudiante|Trabajo del hogar|Voluntariado|Jubilación|Buscando empleo|Profesional independiente',
};
const categories=Object.entries(groups).flatMap(([group,values])=>values.split('|').map(name=>({name,group})));
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export default function ConnectOccupation({value,onChange}:{value:string;onChange:(value:string)=>void}) {
 const id=useId();const [open,setOpen]=useState(false),[active,setActive]=useState(-1);
 const query=normalize(value.trim());const matches=categories.filter(item=>normalize(`${item.name} ${item.group}`).includes(query)).slice(0,8);
 const options=[...matches,...(query&&!categories.some(item=>normalize(item.name)===query)?[{name:value.trim(),group:'Usar mi propia actividad'}]:[])];
 function select(name:string){onChange(name);setOpen(false);setActive(-1);}
 return <div className="connect-occupation" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false)}}><label htmlFor={id}>¿A qué te dedicas? <small>Opcional</small></label><div className="connect-occupation-input"><Search size={17} aria-hidden="true"/><input id={id} role="combobox" aria-autocomplete="list" aria-expanded={open&&options.length>0} aria-controls={`${id}-options`} aria-activedescendant={open&&active>=0?`${id}-${active}`:undefined} autoComplete="off" maxLength={80} placeholder="Busca tu profesión o actividad" value={value} onFocus={()=>setOpen(true)} onChange={e=>{onChange(e.target.value);setOpen(true);setActive(-1)}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);setActive(-1)}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);setActive(i=>e.key==='ArrowDown'?Math.min(i+1,options.length-1):Math.max(i-1,0))}if(e.key==='Enter'&&open&&active>=0&&options[active]){e.preventDefault();select(options[active].name)}}}/></div>{open&&options.length>0&&<div id={`${id}-options`} className="connect-occupation-options" role="listbox" aria-label="Profesiones y actividades">{options.map((item,i)=><button id={`${id}-${i}`} key={`${item.name}-${item.group}`} type="button" role="option" aria-selected={active===i} onMouseDown={e=>e.preventDefault()} onClick={()=>select(item.name)}><span>{item.name}</span><small>{item.group}</small></button>)}</div>}<small className="connect-occupation-help text-xs">Si no aparece, escribe tu propia actividad.</small></div>;
}
