import { ArrowUp, ArrowDown, Plus, Trash2 } from 'lucide-react';
import ConnectSocialIcon from './ConnectSocialIcon';
import { platforms, type SocialLink } from './connect-api';

export default function ConnectLinks({links,onChange}:{links:SocialLink[];onChange:(links:SocialLink[])=>void}) {
 const buttonCount=links.filter(l=>l.display==='button').length;
 function update(index:number,patch:Partial<SocialLink>){onChange(links.map((link,i)=>i===index?{...link,...patch}:link));}
 function move(index:number,direction:number){const next=[...links];[next[index],next[index+direction]]=[next[index+direction],next[index]];onChange(next);}
 return <section className="connect-links-section" aria-label="Editar enlaces"><div className="connect-appearance-heading"><h2>Tus enlaces.</h2><p>Iconos arriba para tus redes y hasta dos botones destacados debajo.</p></div>
 <div className="connect-minimal-links">{links.map((link,index)=><div className="connect-minimal-link" key={index}><div className="connect-minimal-link-top"><span className="connect-link-identity"><ConnectSocialIcon platform={link.platform} size={18}/> {link.display==='button'?'BOTÓN':'ICONO'} {index+1}</span><div><button type="button" className="connect-icon" aria-label={`Subir enlace ${index+1}`} disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp size={15}/></button><button type="button" className="connect-icon" aria-label={`Bajar enlace ${index+1}`} disabled={index===links.length-1} onClick={()=>move(index,1)}><ArrowDown size={15}/></button><button type="button" className="connect-icon" aria-label={`Eliminar enlace ${index+1}`} onClick={()=>onChange(links.filter((_,i)=>i!==index))}><Trash2 size={15}/></button></div></div><label>Mostrar como<select value={link.display||'icon'} onChange={e=>update(index,{display:e.target.value as 'icon'|'button'})}><option value="icon">Icono de red social</option><option value="button" disabled={buttonCount>=2&&link.display!=='button'}>Botón destacado ({buttonCount}/2)</option></select></label><div className="connect-two-fields"><label>Red social<select value={link.platform} onChange={e=>update(index,{platform:e.target.value,label:link.label===link.platform?e.target.value:link.label})}>{platforms.map(platform=><option key={platform}>{platform}</option>)}</select></label><label>Texto del botón<input maxLength={50} value={link.label} onChange={e=>update(index,{label:e.target.value})} placeholder="Mi Instagram"/></label></div><label>Dirección del enlace<input type="url" inputMode="url" autoCapitalize="none" spellCheck={false} maxLength={1000} value={link.url} onChange={e=>update(index,{url:e.target.value})} placeholder={link.platform==='WhatsApp'?'https://wa.me/584121234567':'https://…'}/></label></div>)}</div>
 {!links.length&&<p className="connect-links-empty text-base">Añade tu primera red social o sitio web.</p>}
 <div className="connect-link-add-actions"><button type="button" className="connect-links-add" disabled={links.length>=30} onClick={()=>onChange([...links,{platform:'Instagram',label:'Instagram',url:'',display:'icon'}])}><Plus size={17}/>Añadir icono<span>{links.filter(l=>l.display!=='button').length}</span></button><button type="button" className="connect-links-add" disabled={buttonCount>=2||links.length>=30} onClick={()=>onChange([...links,{platform:'Sitio web',label:'Mi sitio web',url:'',display:'button'}])}><Plus size={17}/>Añadir botón<span>{buttonCount}/2</span></button></div><p className="connect-color-hint text-xs">Hasta 30 enlaces en total. Los iconos se acomodan en varias filas.</p>
 </section>;
}
