import { useRef,useState } from 'react';
import { ArrowUpRight, ChevronDown, ChevronUp, ChevronLeft, ChevronRight, X } from 'lucide-react';
import type { ConnectProfile as Profile } from './connect-api';
import ConnectSocialIcon from './ConnectSocialIcon';
export default function ConnectProfile({profile,photo,preview=false,gallery={}}:{profile:Profile;photo?:string;preview?:boolean;gallery?:Record<number,string>}){
 const [expanded,setExpanded]=useState(false),[selectedPhoto,setSelectedPhoto]=useState<string>();const strip=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null);const t=profile.theme;
 const photos=profile.photos??[];const socialLinks=profile.links.filter(l=>l.display!=='button');const buttons=profile.links.filter(l=>l.display==='button').slice(0,2);
 const photoUrl=(slot:number,updatedAt:string)=>gallery[slot]||`/api/v1/connect/public/${encodeURIComponent(profile.handle)}/gallery/${slot}?v=${encodeURIComponent(updatedAt)}`;
 return <article className={`connect-profile ${preview?'is-preview':''} ${expanded?'is-expanded':''}`} style={{background:t.background,color:t.text,'--profile-panel':t.background,'--profile-ink':t.text} as React.CSSProperties}>
  <div className="connect-portrait" aria-hidden="true">{photo?<img key={photo} src={photo} alt="" onError={e=>{e.currentTarget.style.display='none'}}/>:<span>{profile.displayName.slice(0,1).toUpperCase()||'Q'}</span>}</div>
  <div className="connect-profile-top"><img src="/logo/quicktap-white.png?v=20261002" alt="QuickTap" style={{width:90,height:"auto"}}/><span>@{profile.handle||'tunombre'}</span></div>
  <section className="connect-profile-panel"><button className="connect-panel-handle" aria-label={expanded?'Reducir perfil':'Expandir perfil'} aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}><span/></button><div className="connect-profile-heading"><h1>{profile.displayName||'Tu nombre'}</h1><button className="connect-expand" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}>{expanded?'Ver foto':'Ver perfil'}{expanded?<ChevronDown size={15}/>:<ChevronUp size={15}/>}</button></div>
   <p className="connect-handle text-base">@{profile.handle||'tunombre'}</p><p className="connect-bio text-base">{profile.bio|| (preview?'Una pequeña descripción. Una gran primera impresión.':'')}</p>
   <div className="connect-socials" aria-label="Redes sociales">{socialLinks.map((link,i)=>{return <a key={i} href={preview?undefined:link.url} title={link.label} aria-label={link.label} target="_blank" rel="noopener noreferrer nofollow ugc"><ConnectSocialIcon platform={link.platform} size={19}/></a>})}</div>
   {!!photos.length&&<section className="connect-gallery"><div className="connect-gallery-label"><span>UN POCO DE MI MUNDO</span><span>{photos.length}/5</span></div><div className="connect-gallery-strip" ref={strip}>{photos.map((p,i)=><button key={`${p.slot}-${p.updatedAt}`} onClick={()=>{setSelectedPhoto(photoUrl(p.slot,p.updatedAt));dialog.current?.showModal()}} aria-label={`Ampliar foto ${i+1}`}><img loading="lazy" src={photoUrl(p.slot,p.updatedAt)} alt={p.caption||`Foto ${i+1} de ${profile.displayName}`}/></button>)}</div>{photos.length>2&&<div className="connect-gallery-arrows"><button aria-label="Fotos anteriores" onClick={()=>strip.current?.scrollBy({left:-160,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ChevronLeft size={18}/></button><button aria-label="Fotos siguientes" onClick={()=>strip.current?.scrollBy({left:160,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ChevronRight size={18}/></button></div>}</section>}
   <div className="connect-public-links">{buttons.map((link,i)=>{return <a key={i} href={preview?undefined:link.url} target="_blank" rel="noopener noreferrer nofollow ugc" style={{background:t.button,color:t.buttonText,'--social-cutout':t.button} as React.CSSProperties}><ConnectSocialIcon platform={link.platform} size={17}/><span>{link.label}</span><ArrowUpRight size={17}/></a>})}{!profile.links.length&&preview&&<div className="connect-empty-link">Tus enlaces aparecerán aquí</div>}</div>
   <footer><a href="https://quicktap.club/connect" target={preview?'_blank':undefined} rel="noopener noreferrer">Crea el tuyo con <strong>QuickTap Connect</strong></a></footer>
  </section>
  <dialog className="connect-lightbox" ref={dialog} onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close()}}><button autoFocus onClick={()=>dialog.current?.close()} aria-label="Cerrar foto"><X/></button>{selectedPhoto&&<img src={selectedPhoto} alt={`Foto ampliada de ${profile.displayName}`}/>}</dialog>
 </article>;
}
