import { useEffect,useRef,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { ArrowRight,Check,Copy,Eye,EyeOff,Link as LinkIcon,LogOut,Palette,Radio,Settings,Trash2,UserRound } from 'lucide-react';
import { CONNECT_TOKEN,connectApi,type ConnectProfile as Profile } from './connect-api';
import ProfileView from './FreeMenuPublic';
import FreeMenuEditor from './FreeMenuEditor';
import { emptyMenu } from './connect-api';
import ConnectNfc from './ConnectNfc';
import ConnectUpgrade from './ConnectUpgrade';
import ConnectAppearance from './ConnectAppearance';
import ConnectPhotoButton from './ConnectPhotoButton';
import FreeMenuComparison from './FreeMenuComparison';
import './connect.css';

type Tab='Negocio'|'Menú'|'Apariencia'|'Configuración';

function Brand(){return <Link className="connect-brand" to="/menu-gratis"><img src="/logo/quicktap-logo.png?v=20261002" alt="QuickTap" style={{width:105,height:"auto"}}/><span>menú gratis</span></Link>}
export default function ConnectPage({publicHandle}:{publicHandle?:string}){
 const params=useParams();const handle=publicHandle||params.handle;
 const [profile,setProfile]=useState<Profile|null>(null),[photo,setPhoto]=useState<string>(),[tab,setTab]=useState<Tab>('Negocio'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[nfc,setNfc]=useState(false),[dirty,setDirty]=useState(false);
 const [showPassword,setShowPassword]=useState(false);
 const [mode,setMode]=useState<'register'|'login'|'forgot'|'reset'>('register');
 const [actionToken]=useState(()=>{const q=new URLSearchParams(location.search);return {verify:q.get('verify'),reset:q.get('reset')}});
 const [auth,setAuth]=useState({email:'',password:'',handle:'',displayName:'',occupation:'',acceptTerms:false});
 const verification=useRef<Promise<unknown>|null>(null);
 const photoObject=useRef<string|null>(null);const file=useRef<HTMLInputElement>(null);
 async function loadPhoto(){try{const response=await fetch('/api/v1/connect/me/photo',{headers:{Authorization:`Bearer ${localStorage.getItem(CONNECT_TOKEN)}`}});if(photoObject.current)URL.revokeObjectURL(photoObject.current);if(response.ok){photoObject.current=URL.createObjectURL(await response.blob());setPhoto(photoObject.current)}else setPhoto(undefined);}catch{/* El perfil sigue editable sin la foto. */}}
 async function loadMe(){const data=await connectApi<Profile>('/me');setProfile({...data,menuCatalog:data.menuCatalog??emptyMenu,published:data.menuCatalog?data.published:false});await loadPhoto();}
 useEffect(()=>{let active=true;async function start(){try{if(handle){const res=await fetch(`/api/v1/connect/public/${encodeURIComponent(handle)}`);const body=await res.json();if(!res.ok)throw Error(body.error||'Menú no disponible.');if(body.data.redirectUrl){window.location.replace(body.data.redirectUrl);return;}if(active){setProfile(body.data);setPhoto(`/api/v1/connect/public/${encodeURIComponent(handle)}/photo?v=${encodeURIComponent(body.data.updatedAt)}`);document.title=`${body.data.displayName} · QuickTap Menú Gratis`;}return;}
 if(actionToken.verify||actionToken.reset)history.replaceState(null,'','/menu-gratis');
 if(actionToken.reset){setMode('reset');return;}
 if(actionToken.verify){verification.current??=connectApi('/verify','POST',{token:actionToken.verify});await verification.current;setNotice('Correo confirmado. Ya puedes publicar tu menú.');}
 if(localStorage.getItem(CONNECT_TOKEN))await loadMe();
 }catch(e){if(active)setError((e as Error).message)}finally{if(active)setLoading(false)}}void start();return()=>{active=false;if(photoObject.current)URL.revokeObjectURL(photoObject.current)}},[handle,actionToken.verify,actionToken.reset]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 function edit(patch:Partial<Profile>){setProfile(p=>p?{...p,...patch}:p);setDirty(true);setNotice('');}
 async function submitAuth(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{
 if(mode==='forgot'){const d=await connectApi<{message:string}>('/forgot','POST',{email:auth.email});setNotice(d.message);return;}
 if(mode==='reset'){await connectApi('/reset','POST',{token:actionToken.reset,password:auth.password});localStorage.removeItem(CONNECT_TOKEN);setMode('login');setNotice('Contraseña actualizada. Inicia sesión.');return;}
 const d=await connectApi<{token:string;mailSent?:boolean}>(`/${mode==='register'?'register':'login'}`,'POST',mode==='register'?auth:{email:auth.email,password:auth.password});localStorage.setItem(CONNECT_TOKEN,d.token);await loadMe();if(mode==='register')setNotice(d.mailSent?'Te enviamos un correo para confirmar tu cuenta. Puedes comenzar a diseñar.':'Tu cuenta se creó. Reenvía el correo de confirmación desde Configuración.');
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(){if(!profile)return;setBusy(true);setError('');try{await connectApi('/me/menu','PUT',profile.menuCatalog??emptyMenu);await connectApi('/me','PUT',{occupation:profile.occupation||'',displayName:profile.displayName,bio:profile.bio,links:profile.links,theme:profile.theme,published:!!profile.published});setDirty(false);setNotice(profile.published?'Cambios publicados. Tu tarjeta NFC sigue funcionando.':'Borrador guardado.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(f?:File){if(!f)return;if(f.size>4*1024*1024){setError('Elige una foto de hasta 4 MB.');return;}setBusy(true);setError('');try{const body=new FormData();body.append('photo',f);await connectApi('/me/photo','POST',body);await loadPhoto();setNotice('Foto actualizada.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(profile!.publicUrl!);setNotice('Enlace copiado.')}catch{setError('No se pudo copiar. Copia la dirección que aparece en Configuración.')}}
 if(loading)return <main className="connect-app connect-loading" role="status">Preparando tu espacio…</main>;
 if(handle)return <main className="connect-app connect-public">{profile?<ProfileView profile={profile} photo={photo}/>:<div className="connect-unavailable"><Brand/><h1>Este menú no está disponible.</h1><p>{error}</p><a href="https://quicktap.club/menu-gratis">Crea tu menú gratis</a></div>}</main>;
 const feedback=<>{error&&<div className="connect-feedback error" role="alert">{error}</div>}{notice&&<div className="connect-feedback" role="status"><Check size={17}/>{notice}</div>}</>;
 if(!profile)return <main className="connect-app connect-registration"><header className="connect-minimal-header"><Brand/><button type="button" className="connect-secondary" onClick={()=>{setMode(mode==='login'?'register':'login');setError('');setNotice('');setShowPassword(false)}}>{mode==='login'?'Crear cuenta gratis':'Iniciar sesión'}</button></header><div className="connect-registration-layout"><section className="connect-registration-intro"><span className="connect-eyebrow">TU NEGOCIO, A UN TOQUE</span><h1>{({register:'Tu menú empieza aquí.',login:'Qué bueno verte.',forgot:'Recupera tu acceso.',reset:'Una contraseña nueva.'})[mode]}</h1><p>{mode==='register'?'Hasta 20 productos y 4 categorías. Tu estilo, tus precios en dólares y pedidos por WhatsApp. Gratis.':'Tu menú, siempre contigo.'}</p>{mode==='register'&&<div className="connect-registration-benefits"><span><Check size={13}/>Gratis</span><span><Check size={13}/>Sin tarjeta de crédito</span></div>}{mode==='register'&&<FreeMenuComparison/>}</section><section className="connect-auth connect-registration-form" aria-label={mode==='register'?'Crear cuenta':'Acceso a tu cuenta'}>{feedback}<form onSubmit={submitAuth}>
 {mode==='register'&&<><label>Nombre del negocio<input required maxLength={60} autoComplete="name" value={auth.displayName} onChange={e=>setAuth({...auth,displayName:e.target.value})} placeholder="Nombre de tu negocio"/></label><label>Enlace de tu menú<div className="connect-handle-input"><input required minLength={3} maxLength={30} pattern="[a-z][a-z0-9-]{2,29}" value={auth.handle} onChange={e=>setAuth({...auth,handle:e.target.value.toLowerCase()})} placeholder="tunegocio" autoCapitalize="none"/><span></span></div><small>Elige un nombre permanente para conservar el enlace de tu tarjeta.</small></label></>}
 {mode!=='reset'&&<label>Correo electrónico<input required type="email" autoComplete="email" value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})} placeholder="hola@ejemplo.com"/></label>}
 {mode!=='forgot'&&<label>Contraseña<div className="connect-password-field"><input aria-label="Contraseña" required type={showPassword?'text':'password'} minLength={10} maxLength={72} autoComplete={mode==='login'?'current-password':'new-password'} value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})} placeholder="Al menos 10 caracteres"/><button type="button" aria-label={showPassword?'Ocultar contraseña':'Mostrar contraseña'} aria-pressed={showPassword} onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>}
 {mode==='register'&&<label className="connect-check text-sm font-medium"><input type="checkbox" required checked={auth.acceptTerms} onChange={e=>setAuth({...auth,acceptTerms:e.target.checked})}/><span>Acepto las <a href="/menu-gratis/condiciones" target="_blank" rel="noreferrer">condiciones y privacidad</a> del menú gratuito.</span></label>}
 <button className="connect-primary" disabled={busy}>{busy?'Un momento…':mode==='register'?'Crear mi menú gratis':mode==='forgot'?'Enviar enlace':mode==='reset'?'Guardar contraseña':'Entrar'}<ArrowRight size={18}/></button></form>{mode==='login'&&<button className="connect-text-button" onClick={()=>setMode('forgot')}>Olvidé mi contraseña</button>}{mode==='register'&&<p className="connect-registration-note text-xs">Te enviaremos un correo para confirmar tu cuenta.<br/>Después podrás diseñar y publicar tu menú.</p>}</section><footer className="connect-registration-footer"><span>QuickTap Menú Gratis</span><a href="/menu-gratis/condiciones">Condiciones y privacidad</a></footer></div></main>;
 if(profile.upgradedRestaurant)return <main className="connect-app"><section className="connect-legal"><Brand/><h1>Tu menú ya creció.</h1><p>Productos y fotos transferidos a {profile.upgradedRestaurant.name}. Tu enlace original sigue funcionando.</p><a className="connect-primary" href={`/admin/billing?plan=${profile.upgradePlan||'ESSENTIAL'}`}>Entrar al restaurante y elegir mi plan</a><p>Inicia sesión en el panel con las credenciales del restaurante. Si lo acabas de crear, son las mismas del menú gratis.</p><a className="connect-secondary" href={profile.publicUrl}>Ver mi menú</a></section></main>;
 const tabs:[Tab,typeof UserRound][]=[['Negocio',UserRound],['Menú',LinkIcon],['Apariencia',Palette],['Configuración',Settings]];
 return <main className="connect-app connect-studio"><header className="connect-top"><Brand/><div className="connect-top-actions"><span className="connect-save-state">{dirty?'Cambios sin guardar':profile.published?'Menú público':'Borrador privado'}</span><button className="connect-primary" disabled={busy} onClick={save}>{busy?'Guardando…':'Guardar cambios'}<Check size={16}/></button></div></header><div className="connect-workspace"><aside className="connect-sidebar"><p className="connect-eyebrow">TU ESPACIO</p>{tabs.map(([name,Icon])=><button key={name} className={tab===name?'active':''} aria-current={tab===name?'page':undefined} onClick={()=>setTab(name)}><Icon size={19}/>{name}</button>)}<button className="connect-logout" onClick={()=>{if(dirty&&!confirm('Tienes cambios sin guardar. ¿Salir sin guardarlos?'))return;localStorage.removeItem(CONNECT_TOKEN);setProfile(null);setDirty(false);setPhoto(undefined);setMode('login')}}><LogOut size={18}/>Cerrar sesión</button></aside><section className="connect-editor"><p className="connect-eyebrow">HOLA, {profile.displayName.split(' ')[0].toUpperCase()}</p><h1>{tab==='Negocio'?'La primera impresión de tu negocio.':tab==='Menú'?'Tu carta. Simple y deliciosa.':tab==='Apariencia'?'Un estilo que habla de ti.':'Listo para compartir.'}</h1><p className="connect-subtitle">{tab==='Negocio'?'Haz que te reconozcan antes del primer mensaje.':tab==='Menú'?'Hasta 20 productos, organizados en 4 categorías. Precios en USD.':tab==='Apariencia'?'Elige una combinación o crea la tuya.': 'Publica tu menú y comparte su enlace.'}</p>{feedback}
 {tab==='Negocio'&&<div className="connect-card"><div className="connect-photo-row"><div className="connect-edit-avatar">{photo?<img src={photo} alt="Portada del negocio"/>:<UserRound size={32}/>}</div><div className="connect-cover-actions"><ConnectPhotoButton label={photo?'Cambiar portada':'Añadir portada'} disabled={busy} onClick={()=>file.current?.click()}/><p className="connect-small text-base">Portada · JPG, PNG o WebP · Hasta 4 MB</p>{photo&&<button type="button" className="connect-remove-cover" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await connectApi('/me/photo','DELETE');await loadPhoto();setNotice('Portada eliminada.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><Trash2 size={15}/>Eliminar portada</button>}</div><input ref={file} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/></div><label>Nombre del negocio<input maxLength={60} value={profile.displayName} onChange={e=>edit({displayName:e.target.value})}/></label><label>Descripción<textarea rows={4} maxLength={160} value={profile.bio} onChange={e=>edit({bio:e.target.value})} placeholder="Cuéntales qué preparas y qué hace especial a tu negocio."/><small>{profile.bio.length}/160</small></label><div className="connect-tip"><LinkIcon size={20}/><p>Tu enlace es <strong>@{profile.handle}</strong>. Tu correo de acceso no se muestra públicamente.</p></div></div>}
 {tab==='Menú'&&<FreeMenuEditor profile={profile} onPhotoChange={id=>setProfile(p=>p?{...p,menuImages:[...(p.menuImages??[]).filter(i=>i.productId!==id),{productId:id,updatedAt:new Date().toISOString()}]}:p)} onChange={menuCatalog=>edit({menuCatalog})}/>}
 {tab==='Apariencia'&&<ConnectAppearance theme={profile.theme} onChange={theme=>edit({theme})}/>}
 {tab==='Configuración'&&<><ConnectUpgrade profile={profile} unsaved={dirty} onDone={()=>{setDirty(false);void loadMe()}}/><div className="connect-card"><h2>Tu menú, disponible para todos</h2><label className="connect-check publish text-sm font-medium"><input type="checkbox" checked={!!profile.published} onChange={e=>edit({published:e.target.checked})}/><span>Publicar menú<small>Guarda los cambios para aplicar esta opción.</small></span></label>{!profile.verifiedAt&&<div className="connect-tip"><div><strong>Confirma tu correo</strong><p>Te enviamos un enlace a {profile.email}. Es necesario para publicar.</p><button className="connect-secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await connectApi('/resend','POST');setNotice('Correo enviado. Revisa también la carpeta de spam.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Reenviar correo</button></div></div>}<div className="connect-url">{profile.publicUrl}</div><div className="connect-share-actions"><button className="connect-secondary" onClick={copy}><Copy size={16}/>Copiar enlace</button><a className="connect-secondary" href={profile.publicUrl} target="_blank" rel="noreferrer"><Eye size={16}/>Ver menú</a></div></div><div className="connect-card connect-nfc-card"><Radio size={30}/><h2>Tu menú. Un solo toque.</h2><p>Comparte tu menú con una tarjeta NFC. El mismo enlace muestra tus productos actualizados.</p><button className="connect-primary" disabled={!profile.published||!profile.verifiedAt||dirty} onClick={()=>setNfc(true)}><Radio size={18}/>Vincular con tarjeta NFC</button>{(!profile.published||!profile.verifiedAt||dirty)&&<small>Confirma tu correo, publica el menú y guarda los cambios para vincularlo.</small>}</div><button className="connect-secondary" onClick={()=>{if(dirty&&!confirm('¿Salir sin guardar los cambios?'))return;localStorage.removeItem(CONNECT_TOKEN);setProfile(null);setDirty(false);setPhoto(undefined);setMode('login')}}><LogOut size={16}/>Cerrar sesión</button></>}
 </section><aside className="connect-preview"><div className="connect-preview-heading"><span>VISTA PREVIA EN VIVO</span><span className="connect-live-dot"/></div><div className="connect-phone"><ProfileView profile={profile} photo={photo} preview/></div><p>Así verán tu menú. Simple, visual, tuyo.</p></aside></div>{nfc&&<ConnectNfc url={profile.publicUrl!} onClose={()=>setNfc(false)}/>}</main>;
}
