import { useEffect,useRef,useState } from 'react';
import { Radio, X, Copy, Smartphone, Check } from 'lucide-react';
interface Reader { write(message:{records:{recordType:string;data:string}[]},options:{signal:AbortSignal;overwrite:boolean}):Promise<void> }
export default function ConnectNfc({url,onClose}:{url:string;onClose:()=>void}){
 const [state,setState]=useState<'idle'|'writing'|'done'>('idle');const [message,setMessage]=useState('');const abort=useRef<AbortController|null>(null);const close=useRef<HTMLButtonElement>(null);
 const ReaderClass=(window as unknown as {NDEFReader?:new()=>Reader}).NDEFReader;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;close.current?.focus();return()=>{abort.current?.abort();previous?.focus()}},[]);
 async function write(){if(!ReaderClass)return;const controller=new AbortController();abort.current=controller;setState('writing');setMessage('Acerca la tarjeta a la zona NFC del teléfono.');const timer=setTimeout(()=>controller.abort(),60000);try{await new ReaderClass().write({records:[{recordType:'url',data:url}]},{signal:controller.signal,overwrite:true});setState('done');setMessage('Enlace grabado. Acerca otro teléfono a la tarjeta para comprobar que abre tu menú.');}catch(error){setState('idle');const name=(error as Error).name;setMessage(name==='AbortError'?'Se canceló la escritura. Puedes intentarlo de nuevo.':name==='NotAllowedError'?'Permite el acceso a NFC y vuelve a intentar.':'No se pudo grabar. Revisa que la tarjeta sea NFC NDEF, esté desbloqueada y tenga espacio.');}finally{clearTimeout(timer)}}
 return <div className="connect-overlay" onClick={e=>{if(e.target===e.currentTarget)onClose()}}><section className="connect-sheet" role="dialog" aria-modal="true" aria-labelledby="nfc-title" onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const all=e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), a[href]');const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}>
 <button ref={close} className="connect-icon close" onClick={onClose} aria-label="Cerrar"><X/></button><div className="connect-nfc-symbol">{state==='done'?<Check size={38}/>:<Radio size={38}/>}</div><p className="connect-eyebrow">UN TOQUE. TODO TU MENÚ.</p><h2 id="nfc-title">Vincular tarjeta NFC</h2><p>Tu tarjeta abre este menú. Los cambios que publiques se verán sin volver a grabarla.</p><div className="connect-url">{url}</div>
 {ReaderClass&&window.isSecureContext?<><p className="connect-small text-base">Necesitas una tarjeta NFC compatible y escribible. Esta acción reemplaza el enlace que tenga guardado; no bloquea la tarjeta.</p><button className="connect-primary" disabled={state==='writing'} onClick={write}><Radio size={18}/>{state==='writing'?'Esperando la tarjeta…':state==='done'?'Grabar otra tarjeta':'Grabar enlace en la tarjeta'}</button>{state==='writing'&&<button onClick={()=>abort.current?.abort()}>Cancelar escritura</button>}</>:<div className="connect-tip"><Smartphone/><div><strong>Este navegador no permite grabar NFC.</strong><p>En un teléfono con una aplicación de escritura NFC, elige «Escribir → URL», pega este enlace y acerca la tarjeta. También puedes abrir esta pantalla en Chrome para Android con NFC.</p></div></div>}
 <button className="connect-secondary" onClick={async()=>{try{await navigator.clipboard.writeText(url);setMessage('Enlace copiado.')}catch{setMessage('No se pudo copiar. Selecciona y copia el enlace que aparece arriba.')}}}><Copy size={16}/>Copiar enlace</button><p role="status">{message}</p></section></div>;
}
