import {useEffect,useState} from 'react';
import {Plus,Minus,ShoppingBag,ArrowUpRight,UtensilsCrossed} from 'lucide-react';
import {CONNECT_TOKEN,emptyMenu,type ConnectProfile} from './connect-api';
function ProductPhoto({profile,id,preview}:{profile:ConnectProfile;id:string;preview:boolean}){
 const [url,setUrl]=useState('');const version=profile.menuImages?.find(i=>i.productId===id)?.updatedAt;
 useEffect(()=>{let object='';let active=true;if(!version){setUrl('');return;}
 if(!preview){setUrl(`/api/v1/connect/public/${encodeURIComponent(profile.handle)}/products/${id}/photo?v=${encodeURIComponent(version)}`);return;}
 fetch(`/api/v1/connect/me/products/${id}/photo`,{headers:{Authorization:`Bearer ${localStorage.getItem(CONNECT_TOKEN)}`}}).then(async r=>{if(r.ok){object=URL.createObjectURL(await r.blob());if(active)setUrl(object);else URL.revokeObjectURL(object)}}).catch(()=>{});return()=>{active=false;if(object)URL.revokeObjectURL(object)};
 },[profile.handle,id,preview,version]);
 return url?<img src={url} loading="lazy" alt=""/>:<UtensilsCrossed size={25}/>;
}
export default function FreeMenuPublic({profile,photo,preview=false}:{profile:ConnectProfile;photo?:string;preview?:boolean}){
 const menu=profile.menuCatalog??emptyMenu,t=profile.theme;const [category,setCategory]=useState(''),[cart,setCart]=useState<Record<string,number>>({}),[open,setOpen]=useState(false),[name,setName]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState<{url:string;total:number}|null>(null);
 const visible=menu.products.filter(p=>p.available);const selected=visible.filter(p=>cart[p.id]>0);const total=selected.reduce((n,p)=>n+p.priceCents*cart[p.id],0),count=selected.reduce((n,p)=>n+cart[p.id],0);const money=(n:number)=>`$${(n/100).toFixed(2)}`;
 function quantity(id:string,delta:number){setCart(c=>({...c,[id]:Math.max(0,Math.min(99,(c[id]||0)+delta))}));setReady(null);setError('');}
 async function prepare(){setError('');if(preview){setError('Esta es una vista previa. Publica el menú para recibir pedidos.');return;}if(!name.trim()){setError('Escribe tu nombre.');return;}setBusy(true);try{const response=await fetch(`/api/v1/connect/public/${encodeURIComponent(profile.handle)}/checkout`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,note,items:selected.map(p=>({productId:p.id,quantity:cart[p.id]}))})});const body=await response.json();if(!response.ok)throw Error(body.error||'No pudimos preparar el pedido.');setReady({url:body.data.whatsappUrl,total:body.data.totalCents});}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <article className={`free-menu-public ${preview?'free-menu-preview':''}`} style={{background:t.background,color:t.text,'--profile-panel':t.background,'--menu-ink':t.text,'--menu-button':t.button,'--menu-button-text':t.buttonText} as React.CSSProperties}>
 <header className="free-menu-cover">{photo?<img src={photo} alt={`Portada de ${profile.displayName}`} onError={e=>e.currentTarget.style.display='none'}/>:<div className="free-menu-cover-empty"><UtensilsCrossed size={72}/></div>}<span className="free-menu-wordmark">quicktap · menú</span></header>
 <section className="free-menu-info"><p className="connect-eyebrow">HECHO PARA ANTOJARSE</p><h1>{profile.displayName||'Tu negocio'}</h1><p>{profile.bio|| (preview?'Tu cocina, tu historia y tus mejores platos.':'')}</p><small>Precios en dólares (USD) · Pedidos por WhatsApp</small></section>
 <nav className="free-menu-categories" aria-label="Categorías del menú"><button aria-pressed={!category} onClick={()=>setCategory('')}>Todo</button>{menu.categories.map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</nav>
 <div className="free-menu-products">{visible.filter(p=>!category||p.categoryId===category).map(p=><article className="free-menu-product" key={p.id}><div className="free-menu-product-photo"><ProductPhoto profile={profile} id={p.id} preview={preview}/></div><div className="free-menu-product-copy"><h2>{p.name||'Nombre del producto'}</h2><p>{p.description}</p><div className="free-menu-product-bottom"><strong>{money(p.priceCents)}</strong><div className="free-menu-quantity">{!!cart[p.id]&&<><button aria-label={`Quitar ${p.name}`} onClick={()=>quantity(p.id,-1)}><Minus size={16}/></button><span>{cart[p.id]}</span></>}<button aria-label={`Añadir ${p.name}`} disabled={cart[p.id]>=99} onClick={()=>quantity(p.id,1)}><Plus size={17}/></button></div></div></div></article>)}{!visible.length&&<p className="free-menu-empty text-base">{preview?'Añade tus primeros productos. Aquí comenzará tu menú.':'El negocio está preparando su menú. Vuelve pronto.'}</p>}</div>
 {count>0&&<div className="free-menu-cart"><button className="free-menu-cta" onClick={()=>setOpen(!open)} aria-expanded={open}><ShoppingBag size={19}/><span>Tu pedido · {count}</span><strong>{money(total)}</strong></button>{open&&<section className="free-menu-checkout" aria-label="Tu pedido">{selected.map(p=><div className="free-menu-cart-line" key={p.id}><span>{cart[p.id]} × {p.name}</span><strong>{money(cart[p.id]*p.priceCents)}</strong></div>)}<label>Tu nombre<input value={name} maxLength={80} onChange={e=>{setName(e.target.value);setReady(null)}} autoComplete="name"/></label><label>Nota para el negocio<textarea value={note} maxLength={300} onChange={e=>{setNote(e.target.value);setReady(null)}} placeholder="Indicaciones o consulta sobre tu pedido"/></label><p>El negocio confirmará disponibilidad, entrega y cualquier cargo adicional por WhatsApp. Este menú no procesa pagos.</p>{ready?<a className="free-menu-cta" href={ready.url} target="_blank" rel="noopener noreferrer">Enviar por WhatsApp · {money(ready.total)}<ArrowUpRight size={18}/></a>:<button className="free-menu-cta" disabled={busy} onClick={prepare}>{busy?'Preparando…':'Preparar pedido para WhatsApp'}<ArrowUpRight size={18}/></button>}{error&&<p role="alert">{error}</p>}</section>}</div>}
 <footer className="free-menu-footer"><a href="/menu-gratis">Crea tu menú gratis con <strong>QuickTap</strong></a></footer>
 </article>;
}
