import { useState } from 'react';
import { Plus,Trash2,Camera } from 'lucide-react';
import {connectApi,emptyMenu,type ConnectProfile,type FreeMenuCatalog} from './connect-api';
export default function FreeMenuEditor({profile,onChange,onPhotoChange,preview=false}:{profile:ConnectProfile;preview?:boolean;onPhotoChange:(id:string)=>void;onChange:(menu:FreeMenuCatalog)=>void}){
 const menu=profile.menuCatalog??emptyMenu;const [error,setError]=useState(''),[busy,setBusy]=useState('');
 const update=(id:string,patch:Partial<FreeMenuCatalog['products'][number]>)=>onChange({...menu,products:menu.products.map(p=>p.id===id?{...p,...patch}:p)});
 async function photo(id:string,file?:File){if(!file)return;if(preview){setError('Las fotos de productos se guardan desde tu cuenta. Esta vista previa no publica datos.');return;}setError('');setBusy(id);try{await connectApi('/me/menu','PUT',menu);const body=new FormData();body.append('photo',file);await connectApi(`/me/products/${id}/photo`,'POST',body);onPhotoChange(id);setError('Foto guardada.');}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 return <div className="connect-card free-menu-editor"><label>WhatsApp para recibir pedidos<input inputMode="tel" placeholder="584121234567" maxLength={15} value={menu.whatsapp} onChange={e=>onChange({...menu,whatsapp:e.target.value.replace(/[^0-9]/g,'')})}/><small>Código de país y número, sin + ni espacios. Será el destino de los pedidos.</small></label>
 <div className="free-menu-section-title"><h2>Categorías <small>{menu.categories.length}/4</small></h2><button className="connect-secondary" disabled={menu.categories.length>=4} onClick={()=>onChange({...menu,categories:[...menu.categories,{id:crypto.randomUUID(),name:'Nueva categoría'}]})}><Plus size={16}/>Añadir</button></div>
 {menu.categories.map(c=><div className="free-menu-category-edit" key={c.id}><input aria-label="Nombre de categoría" maxLength={50} value={c.name} onChange={e=>onChange({...menu,categories:menu.categories.map(x=>x.id===c.id?{...x,name:e.target.value}:x)})}/><button className="connect-icon" aria-label={`Eliminar categoría ${c.name}`} onClick={()=>{if(menu.products.some(p=>p.categoryId===c.id)){setError('Mueve los productos a otra categoría antes de eliminar esta.');return;}onChange({...menu,categories:menu.categories.filter(x=>x.id!==c.id)})}}><Trash2 size={17}/></button></div>)}
 <div className="free-menu-section-title"><h2>Productos <small>{menu.products.length}/20</small></h2><button className="connect-secondary" disabled={!menu.categories.length||menu.products.length>=20} onClick={()=>onChange({...menu,products:[...menu.products,{id:crypto.randomUUID(),categoryId:menu.categories[0].id,name:'',description:'',priceCents:0,available:true}]})}><Plus size={16}/>Añadir</button></div>
 {!menu.categories.length&&<p className="connect-small text-base">Crea tu primera categoría para añadir productos.</p>}
 {menu.products.map((p,index)=><article key={p.id} className="free-menu-product-edit"><div className="free-menu-section-title"><strong>Producto {index+1}</strong><button className="connect-icon" aria-label={`Eliminar producto ${index+1}`} onClick={()=>{if(confirm(`¿Eliminar ${p.name||'este producto'} del menú?`))onChange({...menu,products:menu.products.filter(x=>x.id!==p.id)})}}><Trash2 size={16}/></button></div><label>Nombre<input maxLength={80} value={p.name} onChange={e=>update(p.id,{name:e.target.value})}/></label><div className="free-menu-two"><label>Categoría<select value={p.categoryId} onChange={e=>update(p.id,{categoryId:e.target.value})}>{menu.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Precio ($ USD)<input type="number" min="0.01" max="100000" step="0.01" value={p.priceCents?p.priceCents/100:''} onChange={e=>update(p.id,{priceCents:Math.round(Number(e.target.value)*100)})}/></label></div><label>Descripción<textarea maxLength={300} rows={2} value={p.description} onChange={e=>update(p.id,{description:e.target.value})}/></label><div className="free-menu-section-title"><label className="connect-check text-sm font-medium"><input type="checkbox" checked={p.available} onChange={e=>update(p.id,{available:e.target.checked})}/>Disponible</label><label className="connect-secondary text-sm font-medium"><Camera size={17}/>{busy===p.id?'Subiendo…':'Foto del producto'}<input type="file" hidden accept="image/jpeg,image/png,image/webp" disabled={!!busy} onChange={e=>{void photo(p.id,e.target.files?.[0]);e.target.value=''}}/></label></div><small>La foto guarda el catálogo actual. Completa nombres y precios antes de subirla.</small></article>)}
 {error&&<p role="status" className="connect-feedback text-base">{error}</p>}
 </div>;
}
