import { useCallback,useEffect,useRef,useState } from 'react';
import { api } from '@/api/client';
import { PAYMENT_LABELS } from './PaymentDialog.shared';
import type { PaymentMethod } from '@/types';

type Action='PAYMENT'|'ITEMS'|'VOID'|'COLLECT'|'REFUND';
interface Detail {
 accounts:{id:string;name:string;paymentMethods:PaymentMethod[]}[];
 order:{id:string;orderNumber:number;currency:string;updatedAt:string;status:string;adminCorrectedAt:string|null;subtotalBase:string;serviceChargeBase:string;ivaBase:string;totalBase:string;
 items:{id:string;productName:string;quantity:number;unitPrice:string;note:string|null}[];
 payments:{id:string;amountBase:string;method:PaymentMethod;referenceNumber:string|null;changeBase?:string|null;tipBase?:string|null}[]};
 balance:{pendingCollectionBase:string;pendingRefundBase:string};fiscal:boolean;
 logs:{id:string;action:Action;reason:string;actorName:string;createdAt:string;before:{totalBase:string;status:string;items:{productName:string;quantity:number}[];payments:{method:PaymentMethod;amountBase:string}[]};after:Detail['logs'][number]['before']}[];
}
const labels:Record<Action,string>={PAYMENT:'Método de pago',ITEMS:'Corregir comanda',VOID:'Anular pedido',COLLECT:'Registrar cobro',REFUND:'Registrar devolución'};
const inputClass='min-h-11 w-full rounded-xl border border-brand-950/15 bg-white px-3 py-2 text-sm text-brand-950 focus:outline-none focus:ring-2 focus:ring-brand-500/30';
export function OrderCorrectionPanel({orderId,onSaved,livePayment=false}:{orderId:string;onSaved:()=>void;livePayment?:boolean}) {
 const [detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [action,setAction]=useState<Action>(livePayment?'PAYMENT':'ITEMS'),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[saving,setSaving]=useState(false);
 const [method,setMethod]=useState<PaymentMethod>('CASH_USD'),[paymentId,setPaymentId]=useState(''),[reference,setReference]=useState(''),[amount,setAmount]=useState('');
 const [correctedAmount,setCorrectedAmount]=useState('');
 const [changeTreatment,setChangeTreatment]=useState<'KEEP'|'REVERSE'>('KEEP');
 const [settleBalance,setSettleBalance]=useState(true);
 const [inventory,setInventory]=useState<'KEEP'|'ADJUST'>('KEEP');
 const [items,setItems]=useState<{id:string;quantity:number;note:string}[]>([]);
 const [banks,setBanks]=useState<{id:string;name:string;paymentMethods:PaymentMethod[]}[]>([]),[bank,setBank]=useState('');
 const attempt=useRef<{body:string;key:string}|null>(null),busy=useRef(false);
 const load=useCallback(async()=>{
  const response=await api.get(`/orders/${orderId}/corrections`),data=response.data.data as Detail;
  setDetail(data);setBanks(data.accounts ?? []);setItems(data.order.items.map(i=>({id:i.id,quantity:i.quantity,note:i.note??''})));
  if(data.order.status==='CANCELLED'){setAction('REFUND');setAmount(data.balance.pendingRefundBase);}
  const first=livePayment?data.order.payments.find(p=>Number(p.amountBase)>0):data.order.payments[0];if(first){setPaymentId(first.id);setMethod(first.method);setReference(first.referenceNumber??'');}
 },[orderId,livePayment]);
 useEffect(()=>{load().catch(e=>setError(e.response?.data?.error??'No se pudo cargar el pedido.'));},[load]);
 function chooseAction(value:Action){setAction(value);setConfirmed(false);setError('');setBank('');setAmount(detail?(value==='COLLECT'?detail.balance.pendingCollectionBase:detail.balance.pendingRefundBase):'');}
 async function save(){
  if(busy.current||!detail||!confirmed) return;
  busy.current=true;setSaving(true);setError('');setMessage('');
  const payload={action,version:detail.order.updatedAt,reason,...(action==='PAYMENT'?{paymentId,method,...(correctedAmount!==''?{amountBase:Number(correctedAmount)}:{}),...(livePayment?{settleBalance:correctedAmount===''&&settleBalance,changeTreatment}:{}),referenceNumber:reference,bankAccountId:bank||undefined}:{}),...(action==='ITEMS'?{items,inventory}:{}),...(action==='VOID'?{inventory}:{}),...(['COLLECT','REFUND'].includes(action)?{method,amountBase:Number(amount),referenceNumber:reference,bankAccountId:bank||undefined}:{})};
  const serialized=JSON.stringify(payload);
  if(attempt.current?.body!==serialized) attempt.current={body:serialized,key:crypto.randomUUID()};
  try{await api.post(`/orders/${orderId}/corrections`,{...payload,requestKey:attempt.current.key});attempt.current=null;setCorrectedAmount('');await load();onSaved();setConfirmed(false);setReason('');setMessage('Cambio registrado. Los cobros y el historial original se conservaron.');}
  catch(e:any){setError(e.response?.data?.error??'No se pudo confirmar el cambio. Reintenta sin cerrar esta ventana.');}
  finally{busy.current=false;setSaving(false);}
 }
 if(!detail)return <p role="status" className="p-4 text-base">{error||'Cargando información del pedido…'}</p>;
 const cashAction=['PAYMENT','COLLECT','REFUND'].includes(action);
 const money=(value:string|number)=>`${detail.order.currency} ${Number(value).toFixed(2)}`;
 const nextSubtotal=items.reduce((n,i)=>n+i.quantity*Number(detail.order.items.find(x=>x.id===i.id)?.unitPrice??0),0);
 const oldSubtotal=Number(detail.order.subtotalBase),nextTotal=Number(detail.order.totalBase)+(nextSubtotal-oldSubtotal)*(1+(oldSubtotal?(Number(detail.order.serviceChargeBase)+Number(detail.order.ivaBase))/oldSubtotal:0));
 return <section aria-label="Corrección administrativa" className="mt-4 space-y-4 rounded-2xl border border-brand-950/10 bg-brand-950/[0.025] p-4 sm:p-5">
  <div><h3 className="font-semibold text-brand-950">{livePayment?'Corregir pago':'Corrección administrativa'} · #{detail.order.orderNumber}</h3><p className="mt-1 text-brand-950/60 text-xs">Disponible para dueño, administrador y caja. El motivo y las versiones anterior y nueva quedan registrados. Los cierres de caja ya emitidos no se reescriben.</p></div>
  <div className="grid gap-2 sm:grid-cols-2">
   <p className="rounded-xl bg-white p-3 text-base">Pendiente de cobro <strong className="block">{money(detail.balance.pendingCollectionBase)}</strong></p>
   <p className="rounded-xl bg-white p-3 text-base">Pendiente de devolución <strong className="block">{money(detail.balance.pendingRefundBase)}</strong></p>
  </div>
  {detail.fiscal?<p role="alert" className="rounded-xl bg-amber-50 p-3 text-amber-900 text-base">Pedido con factura fiscal emitida o solicitada. No se permite modificarlo ni anularlo desde aquí.</p>:<fieldset disabled={saving} className="space-y-4">
   <label className="block text-sm font-medium">¿Qué necesitas corregir?<select aria-label="Tipo de corrección" value={action} onChange={e=>chooseAction(e.target.value as Action)} className={`${inputClass} mt-1`}>
    {(Object.entries(labels) as [Action,string][]).filter(([key])=>(!livePayment||key==='PAYMENT')&&(detail.order.status!=='CANCELLED'||key==='REFUND')&&(key!=='PAYMENT'||detail.order.payments.length>0)).map(([key,label])=><option key={key} value={key}>{label}</option>)}
   </select></label>
   {action==='PAYMENT'&&<label className="block text-sm font-medium">Cobro original<select aria-label="Cobro original" className={`${inputClass} mt-1`} value={paymentId} onChange={e=>{setCorrectedAmount('');setPaymentId(e.target.value);const p=detail.order.payments.find(p=>p.id===e.target.value)!;setMethod(p.method);setReference(p.referenceNumber??'');setBank('');}}>{detail.order.payments.filter(p=>!livePayment||Number(p.amountBase)>0).map((p,i)=><option key={p.id} value={p.id}>Pago {i+1} · {PAYMENT_LABELS[p.method]} · {money(p.amountBase)}</option>)}</select></label>}
   {action==='PAYMENT'&&<label className="block text-sm font-medium">Monto correcto del pago ({detail.order.currency})<input aria-label="Monto correcto del pago" type="number" min="0.01" max="1000000" step="0.01" value={correctedAmount} placeholder={detail.order.payments.find(p=>p.id===paymentId)?.amountBase} onChange={e=>{setCorrectedAmount(e.target.value);setConfirmed(false);}} className={`${inputClass} mt-1`}/><span className="mt-1 block text-xs text-brand-950/60">Importe aplicado al pedido, sin propina ni vuelto. Sustituye el monto registrado; no cambia el precio del pedido. Vacío conserva el cálculo anterior.</span></label>}
   {livePayment&&<div className="rounded-xl bg-white p-3 text-sm"><label className="flex gap-2 text-sm font-medium"><input type="checkbox" checked={correctedAmount===''&&settleBalance} onChange={e=>{setCorrectedAmount('');setSettleBalance(e.target.checked);setConfirmed(false);}}/>Incluir el saldo pendiente en el pago corregido</label><p className="mt-2 text-base">Pago correcto: <strong>{money((correctedAmount!==''?Number(correctedAmount):Number(detail.order.payments.find(p=>p.id===paymentId)?.amountBase??0)+(settleBalance?Number(detail.balance.pendingCollectionBase):0))+(changeTreatment==='KEEP'?Number(detail.order.payments.find(p=>p.id===paymentId)?.changeBase??0):0))}</strong> (incluye el vuelto conservado; más la propina original, si existe). Sustituye el cobro anterior; no lo duplica.</p></div>}
   {livePayment&&Number(detail.order.payments.find(p=>p.id===paymentId)?.changeBase)>0&&<label className="block text-sm font-medium">Vuelto original: {money(detail.order.payments.find(p=>p.id===paymentId)?.changeBase??0)}<select className={`${inputClass} mt-1`} value={changeTreatment} onChange={e=>{setChangeTreatment(e.target.value as 'KEEP'|'REVERSE');setConfirmed(false);}}><option value="KEEP">Sí se entregó: conservar el vuelto</option><option value="REVERSE">No se entregó: anular el registro del vuelto</option></select><span className="mt-2 block text-xs">{changeTreatment==='KEEP'?'El cobro recibido incluye también el vuelto que ya entregaste.':'Se revierte la salida registrada y se cobra únicamente el importe corregido.'}</span></label>}
   {action==='ITEMS'&&<div className="space-y-3">{detail.order.items.map(original=>{const item=items.find(i=>i.id===original.id)!;return <div key={item.id} className="grid grid-cols-[1fr_90px] gap-2 rounded-xl bg-white p-3"><label className="self-center text-sm font-medium" htmlFor={`quantity-${item.id}`}>{original.productName} <span className="block text-xs text-brand-950/50">{money(original.unitPrice)} por unidad</span></label><input id={`quantity-${item.id}`} className={inputClass} type="number" min="0" max="999" step="1" value={item.quantity} onChange={e=>setItems(items.map(i=>i.id===item.id?{...i,quantity:Number(e.target.value)}:i))}/><input aria-label={`Nota de ${original.productName}`} placeholder="Nota de la comanda" value={item.note} maxLength={200} className={`${inputClass} col-span-2`} onChange={e=>setItems(items.map(i=>i.id===item.id?{...i,note:e.target.value}:i))}/></div>;})}<p className="text-base">Total estimado corregido: <strong>{money(nextTotal)}</strong>. Cantidad 0 elimina el producto del importe. Se conservan las tasas originales y los cargos de envío y envases.</p></div>}
   {(action==='ITEMS'||action==='VOID')&&<label className="block text-sm font-medium">Inventario<select aria-label="Tratamiento del inventario" value={inventory} onChange={e=>setInventory(e.target.value as 'KEEP'|'ADJUST')} className={`${inputClass} mt-1`}><option value="KEEP">Conservar consumo: los productos sí se prepararon</option><option value="ADJUST">Ajustar existencias: fue un error de registro</option></select><span className="mt-1 block text-xs text-brand-950/60">Solo afecta el inventario de pedidos servidos. El ajuste usa las recetas actuales; no devuelve comida preparada al almacén.</span></label>}
   {action==='VOID'&&<p className="rounded-xl bg-red-50 p-3 text-red-800 text-base">La venta quedará anulada, no borrada. Sus cobros se conservan y el dinero recibido quedará pendiente de devolver, incluyendo las propinas cobradas.</p>}
   {cashAction&&<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Método de pago<select aria-label="Método de pago de corrección" className={`${inputClass} mt-1`} value={method} onChange={e=>{setMethod(e.target.value as PaymentMethod);setBank('');}}>{Object.entries(PAYMENT_LABELS).filter(([key])=>key!=='PAYROLL_DEDUCTION').map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="text-sm font-medium">Referencia<input aria-label="Referencia de corrección" value={reference} onChange={e=>setReference(e.target.value)} className={`${inputClass} mt-1`}/></label>{banks.some(b=>b.paymentMethods.includes(method))&&<label className="text-sm font-medium">Cuenta bancaria<select aria-label="Cuenta bancaria de corrección" className={`${inputClass} mt-1`} value={bank} onChange={e=>setBank(e.target.value)}><option value="">Selecciona una cuenta</option>{banks.filter(b=>b.paymentMethods.includes(method)).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}{action!=='PAYMENT'&&<label className="text-sm font-medium">Monto en {detail.order.currency}<input aria-label="Monto de diferencia" type="number" step="0.01" min="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className={`${inputClass} mt-1`}/></label>}</div>}
   <label className="block text-sm font-medium">Motivo obligatorio<textarea aria-label="Motivo de corrección" className={`${inputClass} mt-1`} minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explica el error y la corrección realizada"/></label>
   <label className="flex items-start gap-2 text-sm font-medium"><input type="checkbox" className="mt-1" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>{livePayment?'Confirmo que el registro anterior era incorrecto y que el importe corregido ya fue recibido por este método.':action==='COLLECT'?'Confirmo que este dinero ya fue recibido.':action==='REFUND'?'Confirmo que este dinero ya fue devuelto al cliente.':'Revisé el cambio y autorizo registrarlo con este motivo.'} No se realizan transferencias bancarias desde esta pantalla.</span></label>
   <button type="button" disabled={saving||!confirmed||reason.trim().length<5} onClick={save} className="min-h-11 rounded-xl bg-brand-500 px-5 py-2 text-sm font-semibold text-white disabled:opacity-40">{saving?'Guardando…':'Registrar cambio'}</button>
  </fieldset>}
  {error&&<p role="alert" className="text-red-600 text-base">{error}</p>}{message&&<p role="status" className="text-emerald-700 text-base">{message}</p>}
  {!!detail.logs.length&&<div className="space-y-2 border-t border-brand-950/10 pt-3"><h4 className="text-sm font-semibold">Registro de correcciones</h4>{detail.logs.map(log=><details key={log.id} className="rounded-xl bg-white p-3 text-xs"><summary className="cursor-pointer">{labels[log.action]??'Método previsto'} · {log.actorName} · {new Date(log.createdAt).toLocaleString('es-VE')}</summary><p className="mt-2 text-base">{log.reason}</p><div className="mt-2 grid gap-3 sm:grid-cols-2">{(['before','after'] as const).map(key=><div key={key}><strong>{key==='before'?'Antes':'Después'} · {money(log[key].totalBase)} · {log[key].status==='CANCELLED'?'Anulado':'Registrado'}</strong>{log[key].items.map((i,index)=><p key={index}>{i.quantity} × {i.productName}</p>)}{log[key].payments.map((p,index)=><p key={index}>{PAYMENT_LABELS[p.method]}: {money(p.amountBase)}</p>)}</div>)}</div></details>)}</div>}
 </section>;
}
