import { useState, type FormEvent } from 'react';
import { CalendarDays, ArrowRight, CheckCircle2, RotateCcw } from 'lucide-react';
import { api } from '@/api/client';
import { appointmentColors, appointmentAppearanceStyle, resolveAppointmentPalette, type AppearanceSettings, type AppointmentPalette } from '@/utils/appointment-appearance';
import '../../public/appointment-booking.css';

const presets = [
  { name: 'QuickTap', primary: '#008edf', background: '#f8fafc', accent: '#0f172a', colors: {} },
  { name: 'Oliva', primary: '#dcfa84', background: '#f8f9f5', accent: '#5d6d38', colors: { buttonText:'#263019', soft:'#edf0e5', icon:'#52633c' } },
  { name: 'Arena', primary: '#94724c', background: '#faf7f2', accent: '#6f5135', colors: { buttonText:'#ffffff', soft:'#f0e9df', text:'#362c23', muted:'#827464', field:'#f8f3eb', border:'#e8dfd2', hover:'#fdfaf5' } },
  { name: 'Noche', primary: '#a9c6ff', background: '#15191f', accent: '#a9c6ff', colors: { surface:'#20262e', text:'#f1f4f8', muted:'#abb5c2', border:'#3b4654', soft:'#2c3642', icon:'#c8d6e7', buttonText:'#172436', field:'#192028', fieldText:'#f1f4f8', hover:'#2c3642', successBackground:'#233e33', successText:'#9fdcba', errorBackground:'#442b2e', errorText:'#ffb6bc' } },
] as const;

export default function AppointmentAppearance({settings,onSaved}:{settings:AppearanceSettings & Record<string,unknown>;onSaved:()=>Promise<void>}) {
  const [palette,setPalette]=useState<AppointmentPalette>(()=>resolveAppointmentPalette(settings));
  const [primary,setPrimary]=useState(String(settings.primaryColor||'#008edf'));
  const [background,setBackground]=useState(String(settings.backgroundColor||'#f8fafc'));
  const [accent,setAccent]=useState(String(settings.accentColor||'#0f172a'));
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [saved,setSaved]=useState(false);
  const theme={primaryColor:primary,backgroundColor:background,accentColor:accent,appearance:palette};
  function preset(index:number){const p=presets[index];setPrimary(p.primary);setBackground(p.background);setAccent(p.accent);setPalette(resolveAppointmentPalette({primaryColor:p.primary,appearance:p.colors}));setSaved(false);}
  async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');setSaved(false);try{await api.put('/appointments/settings',{...settings,...theme});await onSaved();setSaved(true);}catch(cause){const e=cause as {response?:{data?:{message?:string;error?:string}}};setError(e.response?.data?.message||e.response?.data?.error||'No se pudieron guardar los colores.');}finally{setBusy(false);}}
  return <section className="apt-card apt-appearance"><div className="apt-section-heading"><div><h2>Colores del enlace público</h2><p className="apt-muted text-base">Personaliza cada superficie. La vista previa cambia mientras eliges los colores.</p></div><button type="button" className="apt-button secondary" onClick={()=>preset(0)}><RotateCcw size={15}/>Restablecer colores</button></div>
    <div className="apt-theme-presets" aria-label="Paletas de colores">{presets.map((p,index)=><button type="button" key={p.name} onClick={()=>preset(index)}><span style={{background:p.primary}}/><span style={{background:p.background}}/>{p.name}</button>)}</div>
    <div className="apt-theme-layout"><form onSubmit={submit} className="apt-theme-form"><fieldset><legend>Identidad</legend><div className="apt-theme-fields"><Color label="Botones y paso activo" value={primary} onChange={v=>{setPrimary(v);setSaved(false);}}/><Color label="Fondo de la página" value={background} onChange={v=>{setBackground(v);setSaved(false);}}/><Color label="Acentos y enfoque" value={accent} onChange={v=>{setAccent(v);setSaved(false);}}/></div></fieldset><fieldset><legend>Detalles del diseño</legend><div className="apt-theme-fields">{Object.entries(appointmentColors).map(([key,[label,fallback]])=><Color key={key} label={label} value={palette[key as keyof AppointmentPalette]||fallback} onChange={value=>{setPalette(p=>({...p,[key]:value}));setSaved(false);}}/>)}</div></fieldset>{error&&<p className="apt-error text-xs" role="alert">{error}</p>}{saved&&<p className="apt-notice text-base" role="status">Colores guardados en tu enlace público.</p>}<button className="apt-button" disabled={busy}>{busy?'Guardando…':'Guardar colores'}</button></form>
    <div className="apt-theme-preview-wrap"><p className="apt-muted text-base">Vista previa en tiempo real</p><div className="booking-page apt-theme-preview" style={appointmentAppearanceStyle(theme)}><div className="booking-brand"><div className="booking-logo"><CalendarDays size={21}/></div><div className="booking-brand-copy"><span>Bienvenido a</span><strong>Tu negocio</strong></div></div><div className="booking-intro"><p>Un momento para ti</p><h1>Tu próxima cita.</h1><div>Un espacio pensado para tus clientes.</div></div><div className="booking-progress"><span className="active"><i>1</i>Servicio</span><span className="complete">Profesional</span><span>Horario</span></div><div className="booking-choice"><span className="booking-choice-icon"><CalendarDays size={20}/></span><span className="booking-choice-body"><strong>Consulta inicial</strong><span>Atención personalizada para ti.</span><span className="booking-choice-meta">60 min<b>€45,00</b></span></span><ArrowRight className="booking-choice-arrow" size={18}/></div><label className="booking-field text-sm font-medium">Tu nombre<input readOnly value="María González" tabIndex={-1}/></label><div className="booking-button">Reservar cita<ArrowRight size={15}/></div><div className="booking-success-icon"><CheckCircle2 size={23}/></div><div className="booking-error">Ejemplo de aviso de error</div><div className="booking-footer">QuickTap Citas</div></div></div></div>
  </section>;
}
function Color({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="apt-theme-color text-sm font-medium"><span>{label}</span><div><input type="color" aria-label={label} value={value} onChange={e=>onChange(e.target.value)}/><input aria-label={`${label} hexadecimal`} value={value} maxLength={7} pattern="#[0-9a-fA-F]{6}" required onChange={e=>onChange(e.target.value)} spellCheck={false}/></div></label>;}
