import { useState } from 'react';
import { Trash2 } from 'lucide-react';
import { api } from '@/api/client';

type Professional = {id:string;name:string;availability:{id:string;dayOfWeek:number;startTime:string;endTime:string}[]};
export default function AppointmentSchedules({professionals,onSaved}:{professionals:Professional[];onSaved:()=>void}) {
  const [professionalId,setProfessional]=useState(professionals[0]?.id??'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const selected=professionals.find(p=>p.id===professionalId);const days=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
  const run=async(action:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await action();await onSaved();}catch{setError('No se pudo guardar el horario. Comprueba que la hora final sea posterior y vuelve a intentar.');}finally{setBusy(false);}};
  return <div className="apt-grid two"><section className="apt-card"><h2>Disponibilidad semanal</h2><p className="apt-muted text-base">Los clientes solo pueden escoger horarios habilitados.</p><form className="apt-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>api.post('/appointments/availability',{professionalId,dayOfWeek:Number(f.get('day')),startTime:f.get('start'),endTime:f.get('end')}));}}><label className="apt-field text-sm font-medium">Profesional<select required value={professionalId} onChange={e=>setProfessional(e.target.value)}><option value="" disabled>Selecciona un profesional</option>{professionals.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label className="apt-field text-sm font-medium">Día<select name="day" defaultValue={1}>{days.map((day,i)=><option value={i} key={day}>{day}</option>)}</select></label><div className="apt-form-grid"><label className="apt-field text-sm font-medium">Desde<input name="start" type="time" required defaultValue="09:00"/></label><label className="apt-field text-sm font-medium">Hasta<input name="end" type="time" required defaultValue="17:00"/></label></div>{error&&<p className="apt-error text-xs" role="alert">{error}</p>}<button className="apt-button" disabled={busy||!professionalId}>{busy?'Guardando…':'Agregar horario'}</button></form></section><section className="apt-card"><h2>Horario de {selected?.name||'tu equipo'}</h2>{!selected?.availability.length&&<p className="apt-muted mt-5 text-base">Todavía no hay franjas. Agrega la primera para habilitar reservas.</p>}{[...(selected?.availability||[])].sort((a,b)=>a.dayOfWeek-b.dayOfWeek||a.startTime.localeCompare(b.startTime)).map(a=><div key={a.id} className="apt-appointment"><div className="apt-appointment-info"><h3>{days[a.dayOfWeek]}</h3><p>{a.startTime} – {a.endTime}</p></div><button className="apt-button secondary" disabled={busy} aria-label={`Eliminar horario ${days[a.dayOfWeek]} ${a.startTime}`} onClick={()=>{if(window.confirm('¿Eliminar esta franja? Las citas existentes no se cancelarán.'))void run(()=>api.delete(`/appointments/availability/${a.id}`));}}><Trash2 size={17}/></button></div>)}</section></div>;
}
