import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowDown, ArrowUpRight, Check, QrCode, UtensilsCrossed, ChefHat, CreditCard, Bike, Boxes, ChartNoAxesCombined, Users, Building2, Sparkles, ShieldCheck, Smartphone } from 'lucide-react';
import { useAuth } from '@/context/AuthContext.shared';
import { useDocumentMeta } from '@/hooks/useDocumentMeta';
import './RestaurantWelcomePage.css';

const sections = [
 { id:'menu', icon:QrCode, title:'Un menú que trabaja contigo.', benefit:'Actualiza tu carta y facilita que tus clientes elijan y pidan.', items:[['Menú digital con QR','Acceso desde el teléfono, con enlaces para compartir y códigos por mesa.'],['Tu marca, a tu manera','Logo, fotografías, categorías, colores, descripción y horarios del negocio.'],['Carta siempre al día','Precios, disponibilidad y productos agotados sin volver a imprimir el menú.'],['Promociones y destacados','Resalta ofertas, productos estrella y especialidades de la casa.'],['Precios en moneda base y bolívares','Conversión con la tasa disponible y tasa conservada en cada pedido.'],['Reservas desde el menú','Recibe solicitudes para que tu equipo confirme y organice la atención.']] },
 { id:'pedidos', icon:UtensilsCrossed, title:'Cada pedido, con todos sus detalles.', benefit:'Conecta lo que pide el cliente con quien lo prepara y quien lo cobra.', items:[['Todos tus canales','Pedidos de mesa, barra, express, delivery y retiro en el local.'],['Variantes y modificadores','Tamaños, ingredientes, extras, cantidades y notas para preparar cada plato.'],['Combos personalizables','Agrupa platos y permite elegir las opciones de cada componente.'],['Gestión de mesas','Zonas, distribución, cuentas abiertas, unión y traslado de mesas.'],['Atención en el salón','Asignación de meseros y avisos de solicitud de servicio o cuenta.'],['Cambios con trazabilidad','Registra el motivo al reducir o retirar productos y conserva el historial.'],['Historial de pedidos','Busca operaciones anteriores y consulta su detalle y documentos.']] },
 { id:'cocina', icon:ChefHat, title:'Una cocina mejor coordinada.', benefit:'Cada estación recibe la información que necesita para trabajar.', items:[['Comandas en tiempo real','Consulta los pedidos y actualiza su estado desde la pantalla de cocina.'],['Cocinas y estaciones','Asigna los productos a su área de preparación.'],['Impresión térmica','Comandas por impresora, pruebas y reimpresiones desde la estación configurada.'],['Notas útiles en la comanda','Platos, cantidades, elecciones y observaciones, sin descripciones publicitarias.'],['Seguimiento de impresión','Registro de envíos y respuestas de la estación; la respuesta no confirma la salida física del papel.'],['Tiempos por plato','Consulta los tiempos de preparación para revisar la operación.'],['Pantallas de atención','Menú en TV, vista de pedidos listos y kiosco de autoservicio.']] },
 { id:'cobros', icon:CreditCard, title:'Cobra con claridad. Cierra con control.', benefit:'Entiende cuánto se cobró, por qué medio y qué queda pendiente.', items:[['Métodos de pago configurables','Efectivo, Pago Móvil, transferencias y otros métodos habilitados por tu negocio.'],['Pagos divididos y parciales','Reparte el cobro entre métodos y registra abonos o pagos por productos.'],['Vuelto, propinas y descuentos','Conserva el detalle que explica el total de cada cuenta.'],['Correcciones de cobro','Corrige monto o método con motivo e historial; identifica saldos por cobrar o devolver.'],['Comprobantes y referencias','Adjunta el soporte y consulta los datos del pago registrado.'],['Apertura y cierre de caja','Registra fondos, revisa cobros y conserva el arqueo de cada turno.'],['Documentos del pedido','Imprime comandas y notas de entrega, también desde pedidos antiguos.'],['Control del pago público','Elige si mostrar los métodos en el menú para revisar el pedido antes de cobrar.'],['Cargos configurables','Servicio, envío y productos internos como cajas para llevar.']] },
 { id:'delivery', icon:Bike, title:'Del pedido a la puerta.', benefit:'Organiza entregas y retiros desde un mismo lugar.', items:[['Pedido por WhatsApp','El cliente arma su selección y abre WhatsApp con el detalle para enviarlo.'],['Confirmación del pedido','Revisa lo recibido antes de continuar con la preparación y el cobro.'],['Zonas y tarifas de entrega','Configura áreas de cobertura y costos de envío.'],['Equipo de motorizados','Asigna pedidos y consulta su seguimiento.'],['Mapa y rutas','Herramientas de ubicación según la configuración del servicio de mapas.'],['Finalización de entregas','Controla el saldo y retira de la cola de cocina los pedidos finalizados.']] },
 { id:'inventario', icon:Boxes, title:'Conoce lo que tienes y lo que consumes.', benefit:'Relaciona compras, ingredientes y platos para entender tus existencias.', items:[['Materia prima y existencias','Unidades, cantidades, costo por unidad y mínimos de reposición.'],['Alertas de inventario','Detecta stock bajo y revisa fechas de caducidad de insumos perecederos.'],['Recetas y preparaciones','Vincula ingredientes con los platos y calcula su costo.'],['Consumo vinculado a pedidos','Descuenta insumos de productos y combos con sus recetas configuradas.'],['Rendimiento y merma','Considera limpieza, desperdicios y rendimiento al calcular costos.'],['Compras y proveedores','Registra reposiciones, cotizaciones, referencias y proveedores.'],['Recuentos y transferencias','Ajusta diferencias justificadas y mueve existencias entre sedes.']] },
 { id:'administracion', icon:ChartNoAxesCombined, title:'Tus números, con contexto.', benefit:'Pasa de saber cuánto vendiste a entender cómo funciona tu negocio.', items:[['Resumen y estadísticas','Consulta ventas por período, canales y desempeño de productos.'],['Costos y margen de utilidad','Compara ingresos y costos para revisar la rentabilidad.'],['Estructura de costo','Materia prima, gastos fijos y variables, margen objetivo y precio sugerido.'],['Punto de equilibrio','Estima qué nivel de ventas necesitas para cubrir tus costos.'],['Ingresos y gastos','Clasifica movimientos, adjunta soportes y consulta su historial.'],['Cuentas por cobrar y pagar','Da seguimiento a saldos pendientes de clientes y proveedores.'],['Bancos, caja chica y bóveda','Vincula métodos de pago, registra movimientos y transferencias internas.'],['Contabilidad y libros','Consulta reportes contables, estados financieros y libros disponibles.'],['Reportes y exportaciones','Revisa períodos y descarga la información desde las herramientas de cada módulo.']] },
 { id:'equipo', icon:Users, title:'Cada persona, en su lugar.', benefit:'Da a tu equipo las herramientas que necesita y mantén el control.', items:[['Usuarios y responsabilidades','Dueño, administrador, cajero, mesero, cocina y roles especializados.'],['Permisos de acceso','Limita acciones y áreas según el rol y la configuración de cada usuario.'],['Clientes y CRM','Historial de clientes, contactos y seguimiento comercial.'],['Promociones y cupones','Configura descuentos para acompañar tus acciones comerciales.'],['Nómina y consumos internos','Gestiona las herramientas de personal y consumos habilitadas en administración.'],['Seguridad del panel','Acceso autenticado, bloqueo de pantalla y separación de datos por negocio.']] },
 { id:'sucursales', icon:Building2, title:'Crece sin perder la visión general.', benefit:'Administra distintas sedes conservando su organización.', items:[['Casa matriz y sucursales','Accede a la gestión de sedes según tu contrato.'],['Resultados consolidados','Compara la operación y revisa los resultados por local.'],['Inventario entre sedes','Consulta existencias y registra transferencias.'],['Módulos y capacidad adicional','Amplía herramientas, usuarios o capacidad desde una membresía existente.']] },
 { id:'facilidades', icon:Smartphone, title:'Más fácil empezar. Más fácil usarlo.', benefit:'Herramientas para configurar el negocio y acompañar el trabajo diario.', items:[['Desde distintos dispositivos','Accede por navegador desde computadora, tablet o teléfono.'],['Aplicaciones disponibles','Opciones para Android y Windows; la disponibilidad depende del dispositivo.'],['QuickStar','Guía de activación para menú, mesas, cobros, equipo y primera operación.'],['Asistente QuickTap','Ayuda con cambios compatibles de catálogo y configuración, con vista previa y confirmación. Usa créditos.'],['Fotos e importación de catálogo','Carga productos e imágenes y utiliza las herramientas de importación disponibles.'],['Avisos y notificaciones','Alertas operativas y de inventario según permisos y configuración.'],['Membresía desde el panel','Consulta tu plan, solicita cambios y envía referencias o comprobantes para revisión.']] },
];

export default function RestaurantWelcomePage(){
 const {login}=useAuth();const navigate=useNavigate();const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useDocumentMeta('Bienvenido a QuickTap · Todo para tu restaurante','Conoce las herramientas de QuickTap para menú, pedidos, cocina, caja, delivery, inventario y administración. Explora el restaurante demo.');
 async function enterDemo(){if(busy)return;setBusy(true);setError('');try{await login('demo@quicktap.club','Demo1234','demo');navigate('/admin');}catch{setError('No pudimos abrir la demo. Intenta nuevamente o entra desde la página de inicio.');}finally{setBusy(false);}}
 return <div className="restaurant-welcome">
  <header className="rw-header"><Link to="/" aria-label="QuickTap, inicio"><img src="/logo/quicktap-white.png" alt="QuickTap" width="118" height="40"/></Link><nav aria-label="Navegación de bienvenida"><a href="#herramientas">Herramientas</a><a href="#vista-demo">El sistema</a><a href="#demo">Demo</a></nav><Link to="/admin/register">Regístrate <ArrowUpRight size={15}/></Link></header>
  <main>
   <section className="rw-hero rw-width"><p className="rw-eyebrow">EL SISTEMA PARA TU RESTAURANTE</p><h1>Tu restaurante.<br/><span>Todo conectado.</span></h1><p className="rw-lead text-base">Del primer pedido al cierre de caja. Descubre las herramientas que conectan a tus clientes, tu equipo y los números de tu negocio.</p><a className="rw-explore" href="#herramientas">Explora las herramientas <ArrowDown size={18}/></a>

   <div className="rw-outcomes"><p><Check/>Pedidos más organizados</p><p><Check/>Equipo coordinado</p><p><Check/>Cobros claros</p><p><Check/>Costos a la vista</p></div></section>
   <section id="herramientas" className="rw-width rw-tools"><div className="rw-intro"><p className="rw-eyebrow">CONOCE EL SISTEMA</p><h2>Todo lo que pasa en tu local,<br/>en un mismo lugar.</h2><p>Explora cada área. Las herramientas disponibles dependen de tu plan, los módulos contratados y la configuración de tu negocio.</p></div>
   <div className="rw-highlights">{[
    {icon:UtensilsCrossed,title:'Del menú a la cocina',text:'Pedidos, mesas y preparación. Cada detalle llega a su lugar.',label:'OPERACIÓN'},
    {icon:CreditCard,title:'Cada cobro, claro',text:'Pagos, caja y saldos. Entiende cada movimiento de tu negocio.',label:'CONTROL'},
    {icon:Boxes,title:'Conoce tus costos',text:'Conecta tus ingredientes, recetas y compras con lo que vendes.',label:'RENTABILIDAD'},
    {icon:ChartNoAxesCombined,title:'Espacio para crecer',text:'Equipo, reportes y sedes. Herramientas para tu siguiente paso.',label:'CRECIMIENTO'},
   ].map((card,index)=><a className="rw-highlight" href={`#${['pedidos','cobros','inventario','administracion'][index]}`} key={card.title}><card.icon size={27}/><span className="rw-card-label">{card.label}</span><h3>{card.title}</h3><p>{card.text}</p><span className="rw-card-bottom">0{index+1}<ArrowUpRight size={20}/></span></a>)}</div>
   <div className="rw-preview" id="vista-demo"><div className="rw-preview-bar"><span/><span/><span/><p>Bunzy Burgers · Datos de demostración</p></div><img src="/images/restaurant-demo/administracion.jpg" alt="Panel de administración de QuickTap con datos de demostración" loading="lazy" width="1280" height="900"/></div>
   <nav className="rw-index" aria-label="Áreas del sistema">{sections.map(s=><a key={s.id} href={`#${s.id}`}><s.icon size={17}/>{({menu:'Menú',pedidos:'Pedidos',cocina:'Cocina',cobros:'Cobros',delivery:'Delivery',inventario:'Inventario',administracion:'Administración',equipo:'Equipo',sucursales:'Sucursales',facilidades:'Facilidades'} as Record<string,string>)[s.id]}</a>)}</nav>
   {sections.map((section,index)=><section className="rw-feature" id={section.id} key={section.id}><div className="rw-feature-heading"><span className="rw-icon"><section.icon size={25}/></span><span className="rw-number">{String(index+1).padStart(2,'0')}</span><h2>{section.title}</h2><p>{section.benefit}</p></div><div className="rw-feature-list">{section.items.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>)}
   <div className="rw-gallery"><figure><img loading="lazy" src="/images/restaurant-demo/productos.jpg" alt="Catálogo de Bunzy Burgers, restaurante demo"/><figcaption>Catálogo del restaurante demo.</figcaption></figure><figure><img loading="lazy" src="/images/restaurant-demo/menu.jpg" alt="Menú público de Bunzy Burgers, restaurante demo"/><figcaption>Menú del restaurante demo.</figcaption></figure></div>
   <aside className="rw-availability"><ShieldCheck size={24}/><div><h3>Elige las herramientas que necesita tu operación.</h3><p>La demo permite explorar distintas áreas; no significa que todas estén incluidas en cada plan. La impresión necesita equipos configurados y la facturación fiscal requiere compatibilidad y habilitación. El asistente usa créditos.</p></div></aside>
   </section>
   <section className="rw-demo" id="demo"><div className="rw-width"><span className="rw-demo-symbol"><Sparkles size={30}/></span><p className="rw-eyebrow">AHORA, CONÓCELO POR DENTRO</p><h2>Tu próxima mesa<br/>está en la demo.</h2><p>Explora un restaurante con datos de ejemplo.<br/>Entra como dueño y recorre la operación a tu ritmo.</p><button onClick={enterDemo} disabled={busy}>{busy?'Abriendo el restaurante…':'Acceder al restaurante demo'}<ArrowUpRight size={20}/></button><small>No necesitas registrarte. Los datos son de demostración.</small>{error&&<p className="rw-error text-xs" role="alert">{error} <Link to="/">Ir al inicio</Link></p>}</div></section>
  </main><footer className="rw-footer rw-width"><img src="/logo/quicktap-white.png" alt="QuickTap" width="100"/><span>Conecta tu operación.</span><Link to="/legal">Información legal</Link></footer>
 </div>;
}
