import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Calculator, Plus, Trash2, Printer, Share2, ArrowRight, CheckCircle2 } from 'lucide-react';
import { Seo } from '@/components/Seo';
import { TextureButton } from '@/components/ui/texture-button';
import { ToolLayout } from './ToolLayout';
import { calculateRecipe, isRecipeDraft, newIngredient, newRecipe, UNITS } from '@/utils/tools/recipe-cost';
import type { CostResult, Ingredient, RecipeDraft, Unit } from '@/utils/tools/recipe-cost';
import { readToolDraft, serializeToolDraft } from '@/utils/tools/draft-storage';
import { trackToolEvent } from '@/utils/tools/analytics';
import './tools.css';

const PATH = '/herramientas/calculadora-costo-plato';
const TITLE = 'Calculadora de costo por plato y food cost gratis | QuickTap';
const DESCRIPTION = 'Calcula el costo de un plato, merma, food cost, margen bruto y precio de venta recomendado. Calculadora gratuita para restaurantes, sin registro.';
const KEY = 'quicktap:tools:recipe-cost:v1';
const structuredData = { '@context': 'https://schema.org', '@type': 'WebApplication', '@id': `https://quicktap.club${PATH}#app`, name: 'Calculadora de costo por plato QuickTap', description: DESCRIPTION, url: `https://quicktap.club${PATH}`, applicationCategory: 'BusinessApplication', operatingSystem: 'Any', inLanguage: 'es', isAccessibleForFree: true, offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' } };
const fieldClass = 'mt-1.5 w-full min-w-0 rounded-xl border border-brand-950/15 bg-white px-3 py-2.5 text-base text-brand-950 outline-none focus:border-brand-logo focus:ring-2 focus:ring-brand-logo/20';
function Field({ label, value, onChange, id, error, text = false, hint }: { label: string; value: string; onChange: (value: string) => void; id: string; error?: string; text?: boolean; hint?: string }) {
  return <div className="min-w-0"><label htmlFor={id} className="text-brand-950/75 text-sm font-medium">{label}</label><input id={id} className={fieldClass} value={value} inputMode={text ? 'text' : 'decimal'} maxLength={text ? 120 : 24} onChange={e => onChange(e.target.value)} aria-invalid={!!error} aria-describedby={error ? `${id}-error` : hint ? `${id}-hint` : undefined} />{hint && <p id={`${id}-hint`} className="mt-1 text-brand-950/60 text-xs">{hint}</p>}{error && <p id={`${id}-error`} className="mt-1 text-red-700 text-xs">{error}</p>}</div>;
}
export default function RecipeCostPage() {
  const [draft, setDraft] = useState<RecipeDraft>(() => { try { return readToolDraft(localStorage.getItem(KEY), isRecipeDraft) ?? newRecipe(); } catch { return newRecipe(); } });
  const [result, setResult] = useState<CostResult | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [storageFailed, setStorageFailed] = useState(false);
  const [diagnosticNotice, setDiagnosticNotice] = useState(false);
  const resultTitle = useRef<HTMLHeadingElement>(null);
  useEffect(() => { try { localStorage.setItem(KEY, serializeToolDraft(draft)); setStorageFailed(false); } catch { setStorageFailed(true); } }, [draft]);
  useEffect(() => {
    let closed: HTMLDetailsElement[] = [];
    const before = () => { closed = [...document.querySelectorAll<HTMLDetailsElement>('.tool-breakdown:not([open])')]; closed.forEach(el => { el.open = true; }); };
    const after = () => { closed.forEach(el => { el.open = false; }); closed = []; };
    window.addEventListener('beforeprint', before); window.addEventListener('afterprint', after);
    return () => { window.removeEventListener('beforeprint', before); window.removeEventListener('afterprint', after); after(); };
  }, []);
  useEffect(() => { if (result) { resultTitle.current?.focus({ preventScroll: true }); resultTitle.current?.scrollIntoView({ behavior: 'auto', block: 'start' }); } }, [result]);
  function update(next: RecipeDraft) { setDraft(next); setResult(null); setErrors({}); }
  function field(key: keyof Omit<RecipeDraft, 'ingredients'>, value: string) { update({ ...draft, [key]: value }); }
  function ingredient(id: string, changes: Partial<Ingredient>) { update({ ...draft, ingredients: draft.ingredients.map(i => i.id === id ? { ...i, ...changes } : i) }); }
  const money = (value: number) => new Intl.NumberFormat('es-VE', { style: 'currency', currency: draft.currency, maximumFractionDigits: 2 }).format(value);
  const percentage = (value: number | null) => value === null ? 'Sin precio' : `${value.toLocaleString('es-VE', { maximumFractionDigits: 1 })}%`;
  function calculate(event: React.FormEvent) {
    event.preventDefault(); const computed = calculateRecipe(draft);
    if (!computed.ok) { setErrors(computed.errors); setResult(null); requestAnimationFrame(() => document.getElementById(Object.keys(computed.errors)[0])?.focus()); return; }
    setErrors({}); setResult(computed.result); trackToolEvent('calculation_completed');
  }
  const status = result?.status === 'healthy' ? { label: 'Margen saludable para tu objetivo', color: 'bg-emerald-50 text-emerald-800 border-emerald-200' } : result?.status === 'tight' ? { label: 'Margen ajustado', color: 'bg-amber-50 text-amber-900 border-amber-200' } : { label: 'Revisa el precio y los costos', color: 'bg-red-50 text-red-800 border-red-200' };
  const shareText = result ? [`${draft.name || 'Mi plato'} · QuickTap`, `Costo por porción: ${money(result.portionCost)}`, `Precio actual: ${money(Number(draft.sale.replace(',', '.')))}`, `Food cost: ${percentage(result.foodCost)} · Margen: ${percentage(result.margin)}`, `Margen bruto estimado por venta: ${money(result.profit)}`, `Precio recomendado (objetivo ${draft.target}%): ${money(result.recommended)}`, ...(result.monthlyProfit !== null ? [`${draft.monthly} ventas al mes: ${money(result.monthlyProfit)} de margen bruto estimado`] : []), 'Incluye ingredientes con merma, empaque y otros variables. No es utilidad neta.', `https://quicktap.club${PATH}`].join('\n') : '';
  return <ToolLayout>
    <Seo title={TITLE} description={DESCRIPTION} path={PATH} />
    <script type="application/ld+json">{JSON.stringify(structuredData)}</script>
    <div className="tool-intro mb-8 max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full bg-brand-logo/10 px-3 py-1.5 text-xs font-semibold text-brand-logo"><Calculator size={15} /> Herramientas gratuitas</span><h1 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Cada plato tiene un costo.<br /><span className="text-brand-logo">Conoce el tuyo.</span></h1><p className="mt-4 leading-relaxed text-brand-950/65 text-base">Calculadora de costo por plato y food cost. Descubre cuánto cuesta tu receta, cuánto deja cada venta y qué precio necesitas para alcanzar tu objetivo. Sin registro.</p></div>
    <div className="grid items-start gap-6 lg:grid-cols-[1.2fr_1fr]">
      <form onSubmit={calculate} noValidate className="tool-form min-w-0 space-y-5">
        <section className="tool-card"><h2 className="text-lg font-semibold">01 · Tu receta</h2><div className="mt-4"><Field id="name" label="Nombre del plato (opcional)" text value={draft.name} onChange={v => field('name', v)} /></div><div className="mt-4 grid grid-cols-2 gap-3"><div><label htmlFor="currency" className="text-sm font-medium">Moneda de todos los importes</label><select id="currency" className={fieldClass} value={draft.currency} onChange={e => field('currency', e.target.value)}><option value="USD">USD · dólares</option><option value="VES">Bs · bolívares</option></select></div><Field id="rate" label="Tasa: Bs por 1 USD (opcional)" value={draft.rate} onChange={v => field('rate', v)} error={errors.rate} /></div><p className="mt-2 leading-relaxed text-brand-950/60 text-xs">La tasa solo muestra una equivalencia del resultado. Cambiar la moneda no convierte los importes escritos. Usa la misma moneda en toda la receta.</p></section>
        <section className="tool-card"><div className="flex items-center justify-between gap-2"><h2 className="text-lg font-semibold">02 · Ingredientes</h2><span className="text-xs text-brand-950/50">{draft.ingredients.length} / 100</span></div><p className="mt-1 leading-relaxed text-brand-950/60 text-xs">El precio es el total pagado por la cantidad comprada. La cantidad utilizada corresponde al ingrediente limpio, después de la merma.</p>
          <div className="mt-5 space-y-4">{draft.ingredients.map((i, index) => { const p = `ingredients.${i.id}.`; return <fieldset key={i.id} className="min-w-0 rounded-2xl bg-brand-950/[0.025] p-3 sm:p-4"><legend className="px-1 text-xs font-semibold text-brand-950/60">Ingrediente {index + 1}</legend><div className="flex items-end gap-2"><div className="min-w-0 flex-1"><Field id={p + 'name'} label="Nombre" text value={i.name} onChange={v => ingredient(i.id, { name: v })} error={errors[p + 'name']} /></div><button type="button" aria-label={`Eliminar ingrediente ${index + 1}`} className="flex size-11 shrink-0 items-center justify-center rounded-xl text-red-600 hover:bg-red-50 disabled:opacity-30" disabled={draft.ingredients.length === 1} onClick={() => update({ ...draft, ingredients: draft.ingredients.filter(row => row.id !== i.id) })}><Trash2 size={18} /></button></div><div className="mt-3 grid grid-cols-2 gap-3"><Field id={p + 'price'} label={`Precio de compra (${draft.currency === 'USD' ? 'USD' : 'Bs'})`} value={i.price} onChange={v => ingredient(i.id, { price: v })} error={errors[p + 'price']} /><Field id={p + 'purchased'} label="Cantidad comprada" value={i.purchased} onChange={v => ingredient(i.id, { purchased: v })} error={errors[p + 'purchased']} /><div><label htmlFor={p + 'purchaseUnit'} className="text-sm font-medium">Unidad de compra</label><select id={p + 'purchaseUnit'} value={i.purchaseUnit} className={fieldClass} onChange={e => { const unit = e.target.value as Unit; ingredient(i.id, { purchaseUnit: unit, usedUnit: UNITS[unit].dimension === UNITS[i.usedUnit].dimension ? i.usedUnit : unit }); }}>{Object.entries(UNITS).map(([key, u]) => <option key={key} value={key}>{u.label}</option>)}</select></div><Field id={p + 'waste'} label="Merma % (opcional)" hint="Parte que se pierde al limpiar o preparar." value={i.waste} onChange={v => ingredient(i.id, { waste: v })} error={errors[p + 'waste']} /><Field id={p + 'used'} label="Cantidad usada en la receta" value={i.used} onChange={v => ingredient(i.id, { used: v })} error={errors[p + 'used']} /><div><label htmlFor={p + 'usedUnit'} className="text-sm font-medium">Unidad utilizada</label><select id={p + 'usedUnit'} className={fieldClass} value={i.usedUnit} onChange={e => ingredient(i.id, { usedUnit: e.target.value as Unit })}>{Object.entries(UNITS).filter(([, u]) => u.dimension === UNITS[i.purchaseUnit].dimension).map(([key, u]) => <option key={key} value={key}>{u.label}</option>)}</select>{errors[p + 'usedUnit'] && <p className="text-red-700 text-xs">{errors[p + 'usedUnit']}</p>}</div></div></fieldset>; })}</div>
          <button type="button" disabled={draft.ingredients.length >= 100} onClick={() => { update({ ...draft, ingredients: [...draft.ingredients, newIngredient()] }); trackToolEvent('ingredient_added'); }} className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-dashed border-brand-logo/50 text-sm font-medium text-brand-logo disabled:opacity-40"><Plus size={17} /> Agregar ingrediente</button>
        </section>
        <section className="tool-card"><h2 className="text-lg font-semibold">03 · Porciones y venta</h2><div className="mt-4 grid grid-cols-2 gap-4">{([['portions', 'Porciones producidas'], ['packaging', 'Empaque por porción'], ['other', 'Otros variables por porción'], ['sale', 'Precio actual por plato'], ['target', 'Food cost objetivo (%)'], ['monthly', 'Ventas al mes (opcional)']] as const).map(([key, label]) => <Field key={key} id={key} label={label} value={draft[key]} onChange={v => field(key, v)} error={errors[key]} />)}</div><p className="mt-3 text-brand-950/60 text-xs">Otros variables: costos por venta como salsas adicionales o comisiones, ingresados como importe. Escribe 0 si no aplican.</p></section>
        {Object.keys(errors).length > 0 && <p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700 text-base">Revisa los campos señalados. {errors.ingredients}</p>}
        <TextureButton type="submit" variant="brand" className="w-full">Calcular mi plato <ArrowRight size={17} /></TextureButton>
        <p className="text-center text-brand-950/60 text-xs" role="status">{storageFailed ? 'No pudimos guardar en este navegador. Mantén esta pestaña abierta.' : 'Tu borrador se conserva 7 días en este navegador. No requiere cuenta.'}</p>
        <button type="button" className="mx-auto block min-h-11 text-xs text-brand-950/60 underline" onClick={() => { update(newRecipe()); }}>Limpiar y empezar otra receta</button>
      </form>
      <aside className="tool-results min-w-0 space-y-5 lg:sticky lg:top-20">
        {!result ? <div className="tool-card border-dashed text-center"><Calculator className="mx-auto my-4 text-brand-logo" size={38} /><h2 className="text-lg font-semibold">Tu resultado, sin sorpresas</h2><p className="mt-3 leading-relaxed text-brand-950/60 text-base">Completa los ingredientes y calcula para ver el costo de cada porción y un precio orientativo.</p><ul className="my-5 space-y-3 text-left text-sm">{['Incluye la merma de tus ingredientes', 'Compara tu precio con tu objetivo', 'Comparte o imprime tu resumen'].map(s => <li key={s} className="flex gap-2"><CheckCircle2 size={17} className="shrink-0 text-emerald-600" />{s}</li>)}</ul></div> : <>
          <section className="tool-card"><h2 ref={resultTitle} tabIndex={-1} className="scroll-mt-24 text-lg font-semibold outline-none">{draft.name || 'Resultado de tu receta'}</h2><p className="mt-1 text-brand-950/60 text-xs">Margen bruto estimado · {draft.portions} porciones · {draft.currency}</p><div className={`mt-4 rounded-xl border px-3 py-2 text-sm font-semibold ${status.color}`}>{status.label}</div><div className="my-5 rounded-2xl bg-brand-950 p-5 text-white"><p className="text-white/70 text-xs">Costo por porción</p><p className="mt-1 break-all text-3xl font-bold">{money(result.portionCost)}</p>{result.rate !== null && <p className="mt-2 text-white/75 text-xs">Equivale a {new Intl.NumberFormat('es-VE', { style: 'currency', currency: draft.currency === 'USD' ? 'VES' : 'USD' }).format(draft.currency === 'USD' ? result.portionCost * result.rate : result.portionCost / result.rate)} · tasa indicada: {draft.rate} Bs/USD</p>}</div><dl className="space-y-3 text-sm">{([['Precio actual por plato', money(Number(draft.sale.replace(',', '.')))], ['Empaque por porción', money(Number(draft.packaging.replace(',', '.')))], ['Otros variables por porción', money(Number(draft.other.replace(',', '.')))], ['Costo total de ingredientes', money(result.ingredientsTotal)], ['Costo total de la receta', money(result.recipeTotal)], ['Food cost · costo / precio', percentage(result.foodCost)], ['Margen bruto · ganancia / precio', percentage(result.margin)], ['Ganancia bruta por plato', money(result.profit)], [`Precio recomendado · objetivo ${draft.target}%`, money(result.recommended)]]).map(([label, value]) => <div key={label} className="flex justify-between gap-3 border-b border-brand-950/5 pb-2"><dt className="text-brand-950/65">{label}</dt><dd className="text-right font-semibold break-all">{value}</dd></div>)}</dl>
            <div className="mt-5 space-y-2 text-sm leading-relaxed"><p>{result.foodCost === null ? 'Ingresa un precio mayor que cero para conocer los porcentajes.' : result.foodCost > Number(draft.target.replace(',', '.')) ? 'Tu food cost está por encima del objetivo. Necesitas aumentar el precio o reducir costos.' : 'Tu food cost cumple el objetivo que definiste.'}</p><p>Este plato genera aproximadamente <strong>{money(result.profit)}</strong> de margen bruto por venta.</p>{result.monthlyProfit !== null && <p>Si vendes <strong>{draft.monthly} unidades al mes</strong>, produciría aproximadamente <strong>{money(result.monthlyProfit)}</strong> de margen bruto.</p>}</div>
            <details className="mt-5 text-xs tool-breakdown"><summary className="cursor-pointer font-semibold">Ver el costo de cada ingrediente</summary><ul className="mt-3 space-y-3">{result.ingredientCosts.map(i => { const input = draft.ingredients.find(row => row.id === i.id)!; return <li key={i.id}><strong>{input.name}: {money(i.cost)}</strong><p className="mt-1 text-brand-950/60 text-base">Aprovechable: {i.usableQuantity.toLocaleString('es-VE', { maximumFractionDigits: 4 })} {UNITS[input.purchaseUnit].label} · {money(i.usableUnitCost)} por {UNITS[input.purchaseUnit].label}. Usado: {input.used} {UNITS[input.usedUnit].label}.</p></li>; })}</ul></details>
            <div className="tool-actions mt-5 grid grid-cols-2 gap-2"><a className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-emerald-50 px-2 text-sm font-semibold text-emerald-800" href={`https://wa.me/?text=${encodeURIComponent(shareText)}`} target="_blank" rel="noopener noreferrer" onClick={() => trackToolEvent('result_shared')}><Share2 size={16} /> WhatsApp</a><button type="button" className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-brand-950/5 px-2 text-sm font-semibold" onClick={() => window.print()}><Printer size={16} /> Imprimir / PDF</button></div>
          </section>
          <section className="tool-conversion tool-card bg-brand-logo/5"><h2 className="text-lg font-semibold">Que tus costos sigan al día</h2><p className="mt-2 text-brand-950/65 text-base">Conecta recetas, inventario y ventas para tomar decisiones con información actualizada.</p><Link className="mt-4 block rounded-xl bg-brand-logo p-3 text-center text-sm font-semibold text-white" to="/inventario-costos" onClick={() => trackToolEvent('quicktap_cta')}>Controla estos costos automáticamente con QuickTap</Link><Link to="/empezar?source=recipe-cost" className="mt-3 block py-2 text-center text-sm font-semibold text-brand-logo" onClick={() => trackToolEvent('trial_start')}>Comienza tu prueba gratuita de 15 días →</Link><button type="button" className="mt-1 w-full py-2 text-center text-sm underline underline-offset-4" onClick={() => { setDiagnosticNotice(true); trackToolEvent('diagnostic_cta'); }}>Realiza el Diagnóstico QuickTap</button>{diagnosticNotice && <p role="status" className="mt-2 text-brand-950/65 text-xs">El Diagnóstico QuickTap estará disponible próximamente. Mientras tanto, puedes explorar la prueba gratuita.</p>}</section>
        </>}
        <section className="tool-card text-xs leading-relaxed text-brand-950/65"><h2 className="mb-3 text-sm font-semibold text-brand-950">Cómo leer estos números</h2><p>La merma reduce la cantidad aprovechable: compra × (1 − merma / 100). El costo usado es precio de compra ÷ cantidad aprovechable × cantidad utilizada, convirtiendo kg/g o litros/ml.</p><p className="mt-2 text-base">Receta = ingredientes + porciones × (empaque + otros variables). Costo por porción = receta ÷ porciones. Food cost = costo por porción ÷ precio × 100. Margen = (precio − costo por porción) ÷ precio × 100. Precio recomendado = costo por porción ÷ (objetivo / 100).</p><p className="mt-2 text-base">Aquí el food cost incluye todos los costos variables ingresados. Verde: cumple tu objetivo. Amarillo: hasta 5 puntos porcentuales por encima. Rojo: más de 5 puntos por encima, pérdida o precio cero. Son criterios orientativos, no una garantía de rentabilidad.</p><p className="mt-2 font-medium text-brand-950 text-base">Es margen bruto estimado, no utilidad neta. No descuenta alquiler, nómina fija, impuestos ni otros gastos que no hayas incluido. Usa un precio de venta sin impuestos y una tasa de cambio de referencia propia.</p></section>
      </aside>
    </div>
  </ToolLayout>;
}
