import { useState } from 'react';
import { projectAssistantEconomics } from '@/utils/assistant-economics';

const usd = (value: number) => `US$${value.toFixed(4)}`;
export default function AssistantEconomics({ availableMicros, economics, unresolvedCalls, rates }: { availableMicros: number; economics?: { chargedCredits: number; settledCostMicros: number }; unresolvedCalls: number; rates: { inputPerMillion: number; outputPerMillion: number } }) {
  const [input, setInput] = useState('5000');
  const [output, setOutput] = useState('2000');
  const [credits, setCredits] = useState('5');
  const [confirmation, setConfirmation] = useState('50');
  const projection = [input, output, credits, confirmation].every(s => s.trim()) ? projectAssistantEconomics(availableMicros, Number(input), Number(output), Number(credits), Number(confirmation), rates.inputPerMillion, rates.outputPerMillion) : null;
  const observed = economics && economics.chargedCredits > 0 && economics.settledCostMicros > 0 && unresolvedCalls === 0 ? economics.settledCostMicros / economics.chargedCredits / 1e6 : null;
  return <section className="qa-card"><h2 className="text-xl font-semibold">Tu costo y el precio para el restaurante</h2><p>Precio de venta: <strong>150 créditos = US$5</strong> · US$0,0333 por crédito. El costo de Gemini depende de las tareas y de las propuestas que no llegan a confirmarse.</p>
    <div className="qa-info">Costo observado de Gemini por 150 créditos consumidos: <strong>{observed === null ? 'Aún no hay datos suficientes' : usd(observed * 150)}</strong><p className="qa-hint text-xs">Gasto de Gemini y créditos consumidos durante el mes UTC. Incluye consultas no confirmadas. Es una media del período; no garantiza el costo futuro.</p></div>
    <h3 className="mt-5 font-semibold">Tu saldo de Gemini expresado en créditos estimados</h3><p className="qa-hint text-xs">Simulación, no saldo real en créditos. Los valores iniciales son un ejemplo editable, no mediciones de tu cuenta.</p>
    <div className="grid gap-3 sm:grid-cols-2"><label>Tokens de entrada por solicitud<input type="number" min="0" step="1" value={input} onChange={e => setInput(e.target.value)} /></label><label>Tokens de salida por solicitud<input type="number" min="0" step="1" value={output} onChange={e => setOutput(e.target.value)} /></label><label>Créditos por tarea confirmada<input type="number" min="1" step="1" value={credits} onChange={e => setCredits(e.target.value)} /></label><label>Solicitudes que se confirman (%)<input type="number" min="1" max="100" value={confirmation} onChange={e => setConfirmation(e.target.value)} /></label></div>
    {projection ? <><div className="grid gap-3 sm:grid-cols-3 mt-4"><div className="qa-info">Créditos totales estimados que puede cubrir el saldo<strong className="block text-xl">{projection.credits.toLocaleString()} créditos</strong><small>{projection.tasks} tareas confirmadas de {projection.calls} consultas</small></div><div className="qa-info">Costo Gemini para QuickTap<strong className="block text-xl">{usd(projection.costPer150Micros / 1e6)}</strong><small>por cada 150 créditos · {usd(projection.costPerCreditMicros / 1e6)} por crédito</small></div><div className="qa-info">Valor equivalente al precio del usuario<strong className="block text-xl">US${projection.retailValueUsd.toFixed(2)}</strong><small>Si se vendieran y consumieran esos créditos. No son ingresos ya cobrados.</small></div></div><p className="qa-hint text-xs">Ejemplo con Gemini 3.8 Flash: US${rates.inputPerMillion}/millón de tokens de entrada y US${rates.outputPerMillion}/millón de salida (incluido razonamiento). No incluye impuestos, comisiones, servidor ni soporte. Las reservas preventivas pueden detener solicitudes antes de agotar el saldo. No es utilidad neta ni una promesa de rendimiento.</p></> : <p role="status" className="qa-info text-base">Completa valores válidos para ver la estimación.</p>}
  </section>;
}
